from .. import Provider as InternetProvider
from faker.utils.decorators import lowercase as lowercase, slugify as slugify
from typing import Any

class Provider(InternetProvider):
    tlds: Any = ...
    safe_email_tlds: Any = ...
    free_email_domains: Any = ...
    email_formats: Any = ...
    def domain_word(self): ...
