from typing import Any

from faker.utils.decorators import lowercase as lowercase
from faker.utils.decorators import slugify as slugify

from .. import Provider as InternetProvider

class Provider(InternetProvider):
    tlds: Any = ...
    safe_email_tlds: Any = ...
    free_email_domains: Any = ...
    email_formats: Any = ...
    def domain_word(self): ...
