from .. import Provider as GeoProvider
from typing import Any

class Provider(GeoProvider):
    poly: Any = ...
    def local_latlng(self): ...
    def local_latitude(self): ...
    def local_longitude(self): ...
