from typing import Any

from .. import Provider as GeoProvider

class Provider(GeoProvider):
    poly: Any = ...
    def local_latlng(self): ...
    def local_latitude(self): ...
    def local_longitude(self): ...
