from . import Connector as Connector
from typing import Any

class ZxJDBCConnector(Connector):
    driver: str = ...
    supports_sane_rowcount: bool = ...
    supports_sane_multi_rowcount: bool = ...
    supports_unicode_binds: bool = ...
    supports_unicode_statements: Any = ...
    description_encoding: Any = ...
    default_paramstyle: str = ...
    jdbc_db_name: Any = ...
    jdbc_driver_name: Any = ...
    @classmethod
    def dbapi(cls): ...
    def create_connect_args(self, url: Any): ...
    def is_disconnect(self, e: Any, connection: Any, cursor: Any): ...
