from .. import Provider as BaseProvider
from typing import Any

class Provider(BaseProvider):
    vat_id_formats: Any = ...
    police_id_formats: Any = ...
    def vat_id(self): ...
    def police_id(self): ...
