from typing import Any

from .. import Provider as BaseProvider

class Provider(BaseProvider):
    vat_id_formats: Any = ...
    police_id_formats: Any = ...
    def vat_id(self): ...
    def police_id(self): ...
