from ...connectors.zxJDBC import ZxJDBCConnector as ZxJDBCConnector
from .base import PGDialect as PGDialect, PGExecutionContext as PGExecutionContext
from typing import Any

class PGExecutionContext_zxjdbc(PGExecutionContext):
    def create_cursor(self): ...

class PGDialect_zxjdbc(ZxJDBCConnector, PGDialect):
    jdbc_db_name: str = ...
    jdbc_driver_name: str = ...
    execution_ctx_cls: Any = ...
    supports_native_decimal: bool = ...
    DataHandler: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
dialect = PGDialect_zxjdbc
