"""
This type stub file was generated by pyright.
"""

from arrow.factory import ArrowFactory
from typing import Any, Optional

"""
Provides the default implementation of :class:`ArrowFactory <arrow.factory.ArrowFactory>`
methods for use as a module API.

"""
_factory = ArrowFactory()
def get(*args, **kwargs):
    """ Calls the default :class:`ArrowFactory <arrow.factory.ArrowFactory>` ``get`` method.

    """
    ...

def utcnow():
    """ Calls the default :class:`ArrowFactory <arrow.factory.ArrowFactory>` ``utcnow`` method.

    """
    ...

def now(tz: Optional[Any] = ...):
    """ Calls the default :class:`ArrowFactory <arrow.factory.ArrowFactory>` ``now`` method.

    """
    ...

def factory(type):
    """ Returns an :class:`.ArrowFactory` for the specified :class:`Arrow <arrow.arrow.Arrow>`
    or derived type.

    :param type: the type, :class:`Arrow <arrow.arrow.Arrow>` or derived.

    """
    ...

__all__ = ["get", "utcnow", "now", "factory"]
