gl_lock = ...
class ManagedWindow():
    fps_limit = ...
    default_win_args = ...
    def __init__(self, **win_args) -> None:
        ...
    
    def __event_loop__(self, **win_args) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def setup(self) -> None:
        ...
    
    def update(self, dt) -> None:
        ...
    
    def draw(self) -> None:
        ...
    


if __name__ == '__main__':
    ...
