from ctypes import Array, c_float
from typing import Any

def cross(a, b) -> tuple[Any, Any, Any]: ...
def dot(a, b): ...
def mag(a) -> float: ...
def norm(a) -> tuple[Any, Any, Any]: ...
def get_sphere_mapping(x, y, width, height) -> tuple[Any, Any, float] | tuple[Any, Any, Any]: ...

rad2deg = ...

def get_spherical_rotatation(p1, p2, width, height, theta_multiplier) -> Array[c_float] | None: ...
