class PlotCamera:
    min_dist = ...
    max_dist = ...
    min_ortho_dist = ...
    max_ortho_dist = ...
    _default_dist = ...
    _default_ortho_dist = ...
    rot_presets = ...
    def __init__(self, window, ortho=...) -> None: ...
    def init_rot_matrix(self) -> None: ...
    def set_rot_preset(self, preset_name) -> None: ...
    def reset(self) -> None: ...
    def mult_rot_matrix(self, rot) -> None: ...
    def setup_projection(self) -> None: ...
    def apply_transformation(self) -> None: ...
    def spherical_rotate(self, p1, p2, sensitivity=...) -> None: ...
    def euler_rotate(self, angle, x, y, z) -> None: ...
    def zoom_relative(self, clicks, sensitivity) -> None: ...
    def mouse_translate(self, x, y, dx, dy) -> None: ...
