from typing import Any, Optional

from .. import BaseProvider as BaseProvider

localized: bool

class Provider(BaseProvider):
    land_coords: Any = ...
    def coordinate(self, center: Optional[Any] = ..., radius: float = ...): ...
    def latitude(self): ...
    def longitude(self): ...
    def latlng(self): ...
    def local_latlng(self, country_code: str = ..., coords_only: bool = ...): ...
    def location_on_land(self, coords_only: bool = ...): ...
