from typing import Any

from ..es import Provider as AddressProvider

class Provider(AddressProvider):
    city_prefixes: Any = ...
    city_adjectives: Any = ...
    city_suffixes: Any = ...
    street_prefixes: Any = ...
    building_number_formats: Any = ...
    postcode_formats: Any = ...
    states: Any = ...
    zip_codes: Any = ...
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    secondary_address_formats: Any = ...
    def city_prefix(self): ...
    def city_suffix(self): ...
    def city_adjective(self): ...
    def street_prefix(self): ...
    def secondary_address(self): ...
    def state(self): ...
    def state_abbr(self): ...
