from .exceptions import ParserError as ParserError
from .iso8601 import parse_iso8601 as parse_iso8601
from typing import Any, Optional

with_extensions: Any
COMMON: Any
DEFAULT_OPTIONS: Any

def parse(text: Any, **options: Any): ...

class _Interval:
    start: Any = ...
    end: Any = ...
    duration: Any = ...
    def __init__(self, start: Optional[Any] = ..., end: Optional[Any] = ..., duration: Optional[Any] = ...) -> None: ...
