from .. import inspect as inspect, util as util
from ..sql import operators as operators
from typing import Any, Optional

class UnevaluatableError(Exception): ...

class EvaluatorCompiler:
    target_cls: Any = ...
    def __init__(self, target_cls: Optional[Any] = ...) -> None: ...
    def process(self, clause: Any): ...
    def visit_grouping(self, clause: Any): ...
    def visit_null(self, clause: Any): ...
    def visit_false(self, clause: Any): ...
    def visit_true(self, clause: Any): ...
    def visit_column(self, clause: Any): ...
    def visit_clauselist(self, clause: Any): ...
    def visit_binary(self, clause: Any): ...
    def visit_unary(self, clause: Any): ...
    def visit_bindparam(self, clause: Any): ...
