from . import interfaces
from ..sql.selectable import ForUpdateArg
from .base import InspectionAttr
from .util import aliased as aliased
from typing import Any, Optional

class Query:
    lazy_loaded_from: Any = ...
    session: Any = ...
    def __init__(self, entities: Any, session: Optional[Any] = ...) -> None: ...
    @property
    def statement(self): ...
    def subquery(self, name: Optional[Any] = ..., with_labels: bool = ..., reduce_columns: bool = ...): ...
    def cte(self, name: Optional[Any] = ..., recursive: bool = ...): ...
    def label(self, name: Any): ...
    def as_scalar(self): ...
    @property
    def selectable(self): ...
    def __clause_element__(self): ...
    def only_return_tuples(self, value: Any) -> None: ...
    @property
    def is_single_entity(self): ...
    def enable_eagerloads(self, value: Any) -> None: ...
    def with_labels(self) -> None: ...
    def enable_assertions(self, value: Any) -> None: ...
    @property
    def whereclause(self): ...
    def with_polymorphic(self, cls_or_mappers: Any, selectable: Optional[Any] = ..., polymorphic_on: Optional[Any] = ...) -> None: ...
    def yield_per(self, count: Any) -> None: ...
    def get(self, ident: Any): ...
    def correlate(self, *args: Any) -> None: ...
    def autoflush(self, setting: Any) -> None: ...
    def populate_existing(self) -> None: ...
    def with_parent(self, instance: Any, property: Optional[Any] = ..., from_entity: Optional[Any] = ...): ...
    def add_entity(self, entity: Any, alias: Optional[Any] = ...) -> None: ...
    def with_session(self, session: Any) -> None: ...
    def from_self(self, *entities: Any): ...
    def values(self, *columns: Any): ...
    def value(self, column: Any): ...
    def with_entities(self, *entities: Any) -> None: ...
    def add_columns(self, *column: Any) -> None: ...
    def add_column(self, column: Any): ...
    def options(self, *args: Any): ...
    def with_transformation(self, fn: Any): ...
    def with_hint(self, selectable: Any, text: Any, dialect_name: str = ...) -> None: ...
    def with_statement_hint(self, text: Any, dialect_name: str = ...): ...
    def get_execution_options(self): ...
    def execution_options(self, **kwargs: Any) -> None: ...
    def with_lockmode(self, mode: Any) -> None: ...
    def with_for_update(self, read: bool = ..., nowait: bool = ..., of: Optional[Any] = ..., skip_locked: bool = ..., key_share: bool = ...) -> None: ...
    def params(self, *args: Any, **kwargs: Any) -> None: ...
    def filter(self, *criterion: Any) -> None: ...
    def filter_by(self, **kwargs: Any): ...
    def order_by(self, *criterion: Any) -> None: ...
    def group_by(self, *criterion: Any) -> None: ...
    def having(self, criterion: Any) -> None: ...
    def union(self, *q: Any): ...
    def union_all(self, *q: Any): ...
    def intersect(self, *q: Any): ...
    def intersect_all(self, *q: Any): ...
    def except_(self, *q: Any): ...
    def except_all(self, *q: Any): ...
    def join(self, *props: Any, **kwargs: Any): ...
    def outerjoin(self, *props: Any, **kwargs: Any): ...
    def reset_joinpoint(self) -> None: ...
    def select_from(self, *from_obj: Any) -> None: ...
    def select_entity_from(self, from_obj: Any) -> None: ...
    def __getitem__(self, item: Any): ...
    def slice(self, start: Any, stop: Any) -> None: ...
    def limit(self, limit: Any) -> None: ...
    def offset(self, offset: Any) -> None: ...
    def distinct(self, *expr: Any) -> None: ...
    def prefix_with(self, *prefixes: Any) -> None: ...
    def suffix_with(self, *suffixes: Any) -> None: ...
    def all(self): ...
    def from_statement(self, statement: Any) -> None: ...
    def first(self): ...
    def one_or_none(self): ...
    def one(self): ...
    def scalar(self): ...
    def __iter__(self) -> Any: ...
    @property
    def column_descriptions(self): ...
    def instances(self, cursor: Any, __context: Optional[Any] = ...): ...
    def merge_result(self, iterator: Any, load: bool = ...): ...
    def exists(self): ...
    def count(self): ...
    def delete(self, synchronize_session: str = ...): ...
    def update(self, values: Any, synchronize_session: str = ..., update_args: Optional[Any] = ...): ...

class LockmodeArg(ForUpdateArg):
    @classmethod
    def parse_legacy_query(self, mode: Any): ...

class _QueryEntity:
    def __new__(cls, *args: Any, **kwargs: Any): ...

class _MapperEntity(_QueryEntity):
    entities: Any = ...
    expr: Any = ...
    def __init__(self, query: Any, entity: Any) -> None: ...
    supports_single_entity: bool = ...
    use_id_for_hash: bool = ...
    mapper: Any = ...
    aliased_adapter: Any = ...
    selectable: Any = ...
    is_aliased_class: Any = ...
    entity_zero: Any = ...
    path: Any = ...
    def setup_entity(self, ext_info: Any, aliased_adapter: Any) -> None: ...
    def set_with_polymorphic(self, query: Any, cls_or_mappers: Any, selectable: Any, polymorphic_on: Any) -> None: ...
    @property
    def type(self): ...
    @property
    def entity_zero_or_selectable(self): ...
    def corresponds_to(self, entity: Any): ...
    def adapt_to_selectable(self, query: Any, sel: Any) -> None: ...
    def row_processor(self, query: Any, context: Any, result: Any): ...
    def setup_context(self, query: Any, context: Any) -> None: ...

class Bundle(InspectionAttr):
    single_entity: bool = ...
    is_clause_element: bool = ...
    is_mapper: bool = ...
    is_aliased_class: bool = ...
    name: Any = ...
    exprs: Any = ...
    c: Any = ...
    def __init__(self, name: Any, *exprs: Any, **kw: Any) -> None: ...
    columns: Any = ...
    def __clause_element__(self): ...
    @property
    def clauses(self): ...
    def label(self, name: Any): ...
    def create_row_processor(self, query: Any, procs: Any, labels: Any): ...

class _BundleEntity(_QueryEntity):
    use_id_for_hash: bool = ...
    bundle: Any = ...
    type: Any = ...
    supports_single_entity: Any = ...
    def __init__(self, query: Any, bundle: Any, setup_entities: bool = ...) -> None: ...
    @property
    def mapper(self): ...
    @property
    def entities(self): ...
    @property
    def entity_zero(self): ...
    def corresponds_to(self, entity: Any): ...
    @property
    def entity_zero_or_selectable(self): ...
    def adapt_to_selectable(self, query: Any, sel: Any) -> None: ...
    def setup_entity(self, ext_info: Any, aliased_adapter: Any) -> None: ...
    def setup_context(self, query: Any, context: Any) -> None: ...
    def row_processor(self, query: Any, context: Any, result: Any): ...

class _ColumnEntity(_QueryEntity):
    expr: Any = ...
    namespace: Any = ...
    type: Any = ...
    use_id_for_hash: Any = ...
    column: Any = ...
    froms: Any = ...
    actual_froms: Any = ...
    entity_zero: Any = ...
    entities: Any = ...
    mapper: Any = ...
    def __init__(self, query: Any, column: Any, namespace: Optional[Any] = ...) -> None: ...
    supports_single_entity: bool = ...
    @property
    def entity_zero_or_selectable(self): ...
    def adapt_to_selectable(self, query: Any, sel: Any) -> None: ...
    selectable: Any = ...
    def setup_entity(self, ext_info: Any, aliased_adapter: Any) -> None: ...
    def corresponds_to(self, entity: Any): ...
    def row_processor(self, query: Any, context: Any, result: Any): ...
    def setup_context(self, query: Any, context: Any) -> None: ...

class QueryContext:
    statement: Any = ...
    from_clause: Any = ...
    whereclause: Any = ...
    order_by: Any = ...
    multi_row_eager_loaders: bool = ...
    adapter: Any = ...
    froms: Any = ...
    for_update: Any = ...
    query: Any = ...
    session: Any = ...
    autoflush: Any = ...
    populate_existing: Any = ...
    invoke_all_eagers: Any = ...
    version_check: Any = ...
    refresh_state: Any = ...
    primary_columns: Any = ...
    secondary_columns: Any = ...
    eager_order_by: Any = ...
    eager_joins: Any = ...
    create_eager_joins: Any = ...
    propagate_options: Any = ...
    attributes: Any = ...
    identity_token: Any = ...
    def __init__(self, query: Any) -> None: ...

class AliasOption(interfaces.MapperOption):
    alias: Any = ...
    def __init__(self, alias: Any) -> None: ...
    def process_query(self, query: Any) -> None: ...
