from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    building_number_formats: Any = ...
    city_formats: Any = ...
    postcode_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    streets: Any = ...
    street_prefixes_long: Any = ...
    street_prefixes_short: Any = ...
    cities: Any = ...
    states: Any = ...
    states_abbr: Any = ...
    countries: Any = ...
    def street(self): ...
    def street_prefix_short(self): ...
    def street_prefix_long(self): ...
    def city_name(self): ...
    def state(self): ...
    def state_abbr(self): ...
    def country(self): ...
