from __future__ import annotations
import numpy as np
from pandas._typing import Scalar, SeriesAxisType
from pandas.core.accessor import DirNamesMixin as DirNamesMixin
from pandas.core.arrays import ExtensionArray as ExtensionArray
from typing import Callable, Generic, List, Optional, Tuple, TypeVar, Union, overload

class PandasObject(DirNamesMixin):
    def __sizeof__(self) -> int: ...

class NoNewAttributesMixin:
    def __setattr__(self, key, value) -> None: ...

class GroupByError(Exception): ...
class DataError(GroupByError): ...
class SpecificationError(GroupByError): ...

class SelectionMixin:
    def ndim(self) -> int: ...
    def __getitem__(self, key): ...
    def aggregate(self, func: Optional[Callable] = ..., *args, **kwargs) -> Union[Scalar, Series, DataFrame]: ...
    agg = aggregate

class ShallowMixin: ...

_T = TypeVar("_T", str, int)

class IndexOpsMixin(Generic[_T]):
    __array_priority__: int = ...
    def transpose(self, *args, **kwargs): ...
    T = ...
    @property
    def shape(self): ...
    @property
    def ndim(self) -> int: ...
    def item(self): ...
    @property
    def nbytes(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def array(self) -> ExtensionArray: ...
    @overload
    def to_numpy(self: Index[str]) -> np.ndarray: ...
    @overload
    def to_numpy(self: Index[int]) -> np.ndarray: ...
    @property
    def empty(self): ...
    def max(self, axis = ..., skipna: bool = ..., *args, **kwargs): ...
    def min(self, axis = ..., skipna: bool = ..., *args, **kwargs): ...
    def argmax(self, axis: Optional[SeriesAxisType] = ..., skipna: bool = ..., *args, **kwargs) -> np.ndarray: ...
    def argmin(self, axis: Optional[SeriesAxisType] = ..., skipna: bool = ..., *args, **kwargs) -> np.ndarray: ...
    def tolist(self) -> List[_T]: ...
    def __iter__(self) : ...
    def hasnans(self): ...
    def value_counts(self, normalize: bool = ..., sort: bool = ..., ascending: bool = ..., bins = ..., dropna: bool = ...): ...
    def unique(self): ...
    def nunique(self, dropna: bool = ...): ...
    @property
    def is_unique(self) -> bool: ...
    @property
    def is_monotonic(self) -> bool: ...
    @property
    def is_monotonic_decreasing(self) -> bool: ...
    @property
    def is_monotonic_increasing(self) -> bool: ...
    def memory_usage(self, deep: bool = ...): ...
    def factorize(
        self, sort: bool = ..., na_sentinel: int = ...
    ) -> Tuple[np.ndarray, Union[np.ndarray, Index, object]]: ...
    def searchsorted(self, value, side: str = ..., sorter = ...): ...
    def drop_duplicates(self, keep: str = ..., inplace: bool = ...): ...
    def duplicated(self, keep: str = ...): ...


from pandas.core.indexes.api import Index as Index
from pandas.core.series import Series
from pandas.core.frame import DataFrame
