#from pandas._typing import ArrayLike as ArrayLike, Dtype as Dtype
#from pandas.arrays import StringArray as StringArray
#from pandas.core.algorithms import take_1d as take_1d
from pandas.core.base import NoNewAttributesMixin as NoNewAttributesMixin
#from pandas.core.construction import extract_array as extract_array
#from pandas.core.dtypes.common import ensure_object as ensure_object, is_bool_dtype as is_bool_dtype, is_categorical_dtype as is_categorical_dtype, is_extension_array_dtype as is_extension_array_dtype, is_integer as is_integer, is_integer_dtype as is_integer_dtype, is_list_like as is_list_like, is_object_dtype as is_object_dtype, is_re as is_re, is_scalar as is_scalar, is_string_dtype as is_string_dtype
#from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCIndexClass as ABCIndexClass, ABCMultiIndex as ABCMultiIndex, ABCSeries as ABCSeries
#from pandas.core.dtypes.missing import isna as isna
#from pandas.util._decorators import Appender as Appender
from typing import Any, List, Optional

def cat_core(list_of_columns: List, sep: str) -> Any: ...
def cat_safe(list_of_columns: List, sep: str) -> Any: ...
def str_count(arr: Any, pat: Any, flags: int = ...): ...
def str_contains(arr: Any, pat: Any, case: bool = ..., flags: int = ..., na: Any = ..., regex: bool = ...): ...
def str_startswith(arr: Any, pat: Any, na: Any = ...): ...
def str_endswith(arr: Any, pat: Any, na: Any = ...): ...
def str_replace(arr: Any, pat: Any, repl: Any, n: int = ..., case: Optional[Any] = ..., flags: int = ..., regex: bool = ...): ...
def str_repeat(arr: Any, repeats: Any): ...
def str_match(arr: Any, pat: Any, case: bool = ..., flags: int = ..., na: Any = ...): ...
def str_extract(arr: Any, pat: Any, flags: int = ..., expand: bool = ...): ...
def str_extractall(arr: Any, pat: Any, flags: int = ...): ...
def str_get_dummies(arr: Any, sep: str = ...): ...
def str_join(arr: Any, sep: Any): ...
def str_findall(arr: Any, pat: Any, flags: int = ...): ...
def str_find(arr: Any, sub: Any, start: int = ..., end: Optional[Any] = ..., side: str = ...): ...
def str_index(arr: Any, sub: Any, start: int = ..., end: Optional[Any] = ..., side: str = ...): ...
def str_pad(arr: Any, width: Any, side: str = ..., fillchar: str = ...): ...
def str_split(arr: Any, pat: Optional[Any] = ..., n: Optional[Any] = ...): ...
def str_rsplit(arr: Any, pat: Optional[Any] = ..., n: Optional[Any] = ...): ...
def str_slice(arr: Any, start: Optional[Any] = ..., stop: Optional[Any] = ..., step: Optional[Any] = ...): ...
def str_slice_replace(arr: Any, start: Optional[Any] = ..., stop: Optional[Any] = ..., repl: Optional[Any] = ...): ...
def str_strip(arr: Any, to_strip: Optional[Any] = ..., side: str = ...): ...
def str_wrap(arr: Any, width: Any, **kwargs: Any): ...
def str_translate(arr: Any, table: Any): ...
def str_get(arr: Any, i: Any): ...
def str_decode(arr: Any, encoding: Any, errors: str = ...): ...
def str_encode(arr: Any, encoding: Any, errors: str = ...): ...
def forbid_nonstring_types(forbidden: Any, name: Optional[Any] = ...): ...
def copy(source: Any): ...

class StringMethods(NoNewAttributesMixin):
    def __init__(self, data: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __iter__(self) -> Any: ...
    def cat(self, others: Optional[Any] = ..., sep: Optional[Any] = ..., na_rep: Optional[Any] = ..., join: str = ...): ...
    def split(self, pat: Optional[Any] = ..., n: int = ..., expand: bool = ...): ...
    def rsplit(self, pat: Optional[Any] = ..., n: int = ..., expand: bool = ...): ...
    def partition(self, sep: str = ..., expand: bool = ...): ...
    def rpartition(self, sep: str = ..., expand: bool = ...): ...
    def get(self, i: Any): ...
    def join(self, sep: Any): ...
    def contains(self, pat: Any, case: bool = ..., flags: int = ..., na: Any = ..., regex: bool = ...) -> Series[bool]: ...
    def match(self, pat: Any, case: bool = ..., flags: int = ..., na: Any = ...): ...
    def replace(self, pat: Any, repl: Any, n: int = ..., case: Optional[Any] = ..., flags: int = ..., regex: bool = ...): ...
    def repeat(self, repeats: Any): ...
    def pad(self, width: Any, side: str = ..., fillchar: str = ...): ...
    def center(self, width: Any, fillchar: str = ...): ...
    def ljust(self, width: Any, fillchar: str = ...): ...
    def rjust(self, width: Any, fillchar: str = ...): ...
    def zfill(self, width: Any): ...
    def slice(self, start: Optional[Any] = ..., stop: Optional[Any] = ..., step: Optional[Any] = ...): ...
    def slice_replace(self, start: Optional[Any] = ..., stop: Optional[Any] = ..., repl: Optional[Any] = ...): ...
    def decode(self, encoding: Any, errors: str = ...): ...
    def encode(self, encoding: Any, errors: str = ...): ...
    def strip(self, to_strip: Optional[Any] = ...): ...
    def lstrip(self, to_strip: Optional[Any] = ...): ...
    def rstrip(self, to_strip: Optional[Any] = ...): ...
    def wrap(self, width: Any, **kwargs: Any): ...
    def get_dummies(self, sep: str = ...): ...
    def translate(self, table: Any): ...
    count: Any = ...
    startswith: Any = ...
    endswith: Any = ...
    findall: Any = ...
    def extract(self, pat: Any, flags: int = ..., expand: bool = ...): ...
    def extractall(self, pat: Any, flags: int = ...): ...
    def find(self, sub: Any, start: int = ..., end: Optional[Any] = ...): ...
    def rfind(self, sub: Any, start: int = ..., end: Optional[Any] = ...): ...
    def normalize(self, form: Any): ...
    def index(self, sub: Any, start: int = ..., end: Optional[Any] = ...): ...
    def rindex(self, sub: Any, start: int = ..., end: Optional[Any] = ...): ...
    len: Any = ...
    lower: Any = ...
    upper: Any = ...
    title: Any = ...
    capitalize: Any = ...
    swapcase: Any = ...
    casefold: Any = ...
    isalnum: Any = ...
    isalpha: Any = ...
    isdigit: Any = ...
    isspace: Any = ...
    islower: Any = ...
    isupper: Any = ...
    istitle: Any = ...
    isnumeric: Any = ...
    isdecimal: Any = ...


from pandas.core.series import Series