from typing import Any, Optional

from .. import BaseProvider as BaseProvider

class Provider(BaseProvider):
    application_mime_types: Any = ...
    audio_mime_types: Any = ...
    image_mime_types: Any = ...
    message_mime_types: Any = ...
    model_mime_types: Any = ...
    multipart_mime_types: Any = ...
    text_mime_types: Any = ...
    video_mime_types: Any = ...
    mime_types: Any = ...
    audio_file_extensions: Any = ...
    image_file_extensions: Any = ...
    text_file_extensions: Any = ...
    video_file_extensions: Any = ...
    office_file_extensions: Any = ...
    file_extensions: Any = ...
    unix_device_prefixes: Any = ...
    def mime_type(self, category: Optional[Any] = ...): ...
    def file_name(
        self, category: Optional[Any] = ..., extension: Optional[Any] = ...
    ): ...
    def file_extension(self, category: Optional[Any] = ...): ...
    def file_path(
        self,
        depth: int = ...,
        category: Optional[Any] = ...,
        extension: Optional[Any] = ...,
    ): ...
    def unix_device(self, prefix: Optional[Any] = ...): ...
    def unix_partition(self, prefix: Optional[Any] = ...): ...
