from .. import Provider as CompanyProvider
from faker.utils.checksums import calculate_luhn as calculate_luhn
from typing import Any

class Provider(CompanyProvider):
    formats: Any = ...
    catch_phrase_words: Any = ...
    bsWords: Any = ...
    company_suffixes: Any = ...
    def catch_phrase(self): ...
    def bs(self): ...
    def company_vat(self): ...
