from typing import Any

def is_bool(obj: Any) -> bool: ...
def is_integer(obj: Any) -> bool: ...
def is_float(obj: Any) -> bool: ...
def is_complex(obj: Any) -> bool: ...
def is_scalar(obj: Any) -> bool: ...
def is_decimal(obj: Any) -> bool: ...
def is_interval(obj: Any) -> bool: ...
def is_list_like(obj: Any) -> bool: ...
def is_number(obj: Any) -> bool: ...
def is_iterator(obj: Any) -> bool: ...
def is_file_like(obj: Any) -> bool: ...
def is_re(obj: Any) -> bool: ...
def is_re_compilable(obj: Any) -> bool: ...
def is_array_like(obj: Any) -> bool: ...
def is_nested_list_like(obj: Any) -> bool: ...
def is_dict_like(obj: Any) -> bool: ...
def is_named_tuple(obj: Any) -> bool: ...
def is_hashable(obj: Any) -> bool: ...
def is_sequence(obj: Any) -> bool: ...
