from pandas.core.frame import DataFrame as DataFrame

def melt(frame: DataFrame, id_vars=..., value_vars=..., var_name=..., value_name=..., col_level=...) -> DataFrame: ...
def lreshape(data: DataFrame, groups, dropna: bool=..., label=...) -> DataFrame: ...
def wide_to_long(df: DataFrame, stubnames, i, j, sep: str=..., suffix: str=...) -> DataFrame: ...
