from .. import Provider as PersonProvider
from typing import Any

class Provider(PersonProvider):
    formats_female: Any = ...
    formats_male: Any = ...
    formats: Any = ...
    first_names_female: Any = ...
    first_names_male: Any = ...
    first_names: Any = ...
    last_names: Any = ...
    prefixes_female: Any = ...
    prefixes_male: Any = ...
    suffixes_female: Any = ...
    suffixes_male: Any = ...
