from typing import Any

from .. import Provider as CompanyProvider

class Provider(CompanyProvider):
    formats: Any = ...
    company_prefixes: Any = ...
    company_suffixes: Any = ...
    def company_prefix(self): ...
