import pyarrow
from typing import Any

def pyarrow_array_to_numpy_and_mask(arr: Any, dtype: Any): ...

class ArrowPeriodType(pyarrow.ExtensionType):
    def __init__(self, freq: Any) -> None: ...
    @property
    def freq(self): ...
    def __arrow_ext_serialize__(self): ...
    @classmethod
    def __arrow_ext_deserialize__(cls, storage_type: Any, serialized: Any): ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...

class ArrowIntervalType(pyarrow.ExtensionType):
    def __init__(self, subtype: Any, closed: Any) -> None: ...
    @property
    def subtype(self): ...
    @property
    def closed(self): ...
    def __arrow_ext_serialize__(self): ...
    @classmethod
    def __arrow_ext_deserialize__(cls, storage_type: Any, serialized: Any): ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
