from typing import Any

def sort_as_subsets(tuples: Any, allitems: Any, deterministic_order: bool = ...) -> None: ...
def sort(tuples: Any, allitems: Any, deterministic_order: bool = ...) -> None: ...
def find_cycles(tuples: Any, allitems: Any): ...
