from typing import Any, Callable

def top_down(rule, fns=...) -> Callable[[Any], Any]: ...
def bottom_up(rule, fns=...) -> Callable[[Any], Any]: ...
def top_down_once(rule, fns=...) -> Callable[[Any], Any]: ...
def bottom_up_once(rule, fns=...) -> Callable[[Any], Any]: ...
def sall(rule, fns=...) -> Callable[..., Any]: ...
