from collections.abc import Generator
from typing import Any, Callable

def treeapply(tree, join, leaf=...): ...
def greedy(tree, objective=..., **kwargs): ...
def allresults(tree, leaf=...): ...
def brute(tree, objective=..., **kwargs) -> Callable[..., Any]: ...
