from .. import Provider as InternetProvider
from faker.utils.decorators import slugify as slugify
from typing import Any

class Provider(InternetProvider):
    user_name_formats: Any = ...
    tlds: Any = ...
    def domain_word(self): ...
