from typing import Literal

def finite_diff_weights(order, x_list, x0=...) -> list[list[list[int]]]: ...
def apply_finite_diff(order, x_list, y_list, x0=...) -> Literal[0]: ...
def differentiate_finite(expr, *symbols, points=..., x0=..., wrt=..., evaluate=...): ...
