def singularities(expression, symbol, domain=...): ...
def monotonicity_helper(expression, predicate, interval=..., symbol=...): ...
def is_increasing(expression, interval=..., symbol=...): ...
def is_strictly_increasing(expression, interval=..., symbol=...): ...
def is_decreasing(expression, interval=..., symbol=...): ...
def is_strictly_decreasing(expression, interval=..., symbol=...): ...
def is_monotonic(expression, interval=..., symbol=...) -> bool: ...
