from .. import Provider as PhoneNumberProvider
from typing import Any

class Provider(PhoneNumberProvider):
    cellphone_formats: Any = ...
    telephone_formats: Any = ...
    toll_foramts: Any = ...
    services_phones_formats: Any = ...
    formats: Any = ...
    def provider_code(self): ...
    def area_code(self): ...
    def cellphone_number(self): ...
    def telephone_number(self): ...
    def service_phone_number(self): ...
    def toll_number(self): ...
    def phone_number(self): ...
