from ..en import Provider as AddressProvider
from typing import Any, Optional

class Provider(AddressProvider):
    postal_code_letters: Any = ...
    city_prefixes: Any = ...
    city_suffixes: Any = ...
    building_number_formats: Any = ...
    street_suffixes: Any = ...
    postal_code_formats: Any = ...
    provinces: Any = ...
    provinces_abbr: Any = ...
    provinces_postcode_prefixes: Any = ...
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    secondary_address_formats: Any = ...
    def province(self): ...
    def province_abbr(self): ...
    def city_prefix(self): ...
    def secondary_address(self): ...
    def postal_code_letter(self): ...
    def postcode(self): ...
    def postcode_in_province(self, province_abbr: Optional[Any] = ...): ...
    def postalcode_in_province(self, province_abbr: Optional[Any] = ...): ...
    def postalcode(self): ...
