from typing import Any

class _HashedTuple(tuple):
    def __hash__(self, hash: Any = ...) -> Any: ...
    def __add__(self, other: Any, add: Any = ...): ...
    def __radd__(self, other: Any, add: Any = ...): ...

def hashkey(*args: Any, **kwargs: Any): ...
def typedkey(*args: Any, **kwargs: Any): ...
