from .. import Provider as CompanyProvider
from typing import Any

class Provider(CompanyProvider):
    formats: Any = ...
    company_suffixes: Any = ...
    company_types: Any = ...
    company_products: Any = ...
    company_nouns: Any = ...
    company_adjectives: Any = ...
    def company_type(self): ...
    def random_company_adjective(self): ...
    def random_company_noun_chain(self): ...
    def random_company_product(self): ...
    def random_company_acronym(self): ...
