from sympy.matrices import Matrix
from sympy.matrices.dense import MutableDenseMatrix

def msigma(i) -> MutableDenseMatrix: ...
def pat_matrix(m, dx, dy, dz): ...
def mgamma(mu, lower=...) -> MutableDenseMatrix: ...

minkowski_tensor = ...

def mdft(n) -> Matrix: ...
