from typing import Any

from .. import Provider as PhoneNumberProvider

class Provider(PhoneNumberProvider):
    cellphone_formats: Any = ...
    formats: Any = ...
    def cellphone_number(self): ...
