from .. import Provider as PhoneNumberProvider
from typing import Any

class Provider(PhoneNumberProvider):
    cellphone_formats: Any = ...
    formats: Any = ...
    def cellphone_number(self): ...
