from .. import Provider as AddressProvider
from typing import Any

class Provider(AddressProvider):
    metro_manila_postcodes: Any = ...
    luzon_province_postcodes: Any = ...
    visayas_province_postcodes: Any = ...
    mindanao_province_postcodes: Any = ...
    postcodes: Any = ...
    metro_manila_lgus: Any = ...
    province_lgus: Any = ...
    luzon_provinces: Any = ...
    visayas_provinces: Any = ...
    mindanao_provinces: Any = ...
    provinces: Any = ...
    partitioned_building_number_formats: Any = ...
    building_unit_number_formats: Any = ...
    building_name_formats: Any = ...
    building_name_suffixes: Any = ...
    subdivision_unit_number_formats: Any = ...
    subdivision_name_formats: Any = ...
    subdivision_name_suffixes: Any = ...
    floor_numbers: Any = ...
    street_suffixes: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    metro_manila_address_formats: Any = ...
    luzon_province_address_formats: Any = ...
    visayas_province_address_formats: Any = ...
    mindanao_province_address_formats: Any = ...
    address_formats: Any = ...
    def metro_manila_postcode(self): ...
    def luzon_province_postcode(self): ...
    def visayas_province_postcode(self): ...
    def mindanao_province_postcode(self): ...
    def postcode(self): ...
    def luzon_province(self): ...
    def visayas_province(self): ...
    def mindanao_province(self): ...
    def province(self): ...
    def standalone_building_number(self): ...
    def partitioned_building_number(self): ...
    def building_number(self): ...
    def ordinal_street_number(self): ...
    def floor_number(self): ...
    def ordinal_floor_number(self): ...
    def floor_unit_number(self): ...
    def building_unit_number(self): ...
    def building_name(self): ...
    def building_name_suffix(self): ...
    def subdivision_block_number(self): ...
    def subdivision_lot_number(self): ...
    def subdivision_unit_number(self): ...
    def subdivision_name(self): ...
    def subdivision_name_suffix(self): ...
    def metro_manila_lgu(self): ...
    def province_lgu(self): ...
    def metro_manila_address(self): ...
    def luzon_province_address(self): ...
    def visayas_province_address(self): ...
    def mindanao_province_address(self): ...
    def address(self): ...
