from .. import Provider as PersonProvider
from typing import Any

class Provider(PersonProvider):
    formats_male: Any = ...
    formats_female: Any = ...
    formats: Any = ...
    first_names_male: Any = ...
    first_names_female: Any = ...
    first_names: Any = ...
    last_names: Any = ...
