from typing import Any

from faker.utils.decorators import slugify as slugify

from .. import Provider as InternetProvider

class Provider(InternetProvider):
    user_name_formats: Any = ...
    tlds: Any = ...
    second_level_domains: Any = ...
    domain_formats: Any = ...
    def domain_word(self): ...
    def domain_name(self, levels: int = ...): ...
