"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

"""Python Compatibility Utilities."""
_environment = None
def coro(gen):
    """Decorator to mark generator as co-routine."""
    ...

def detect_environment():
    """Detect the current environment: default, eventlet, or gevent."""
    ...

def entrypoints(namespace):
    """Return setuptools entrypoints for namespace."""
    ...

def fileno(f):
    """Get fileno from file-like object."""
    ...

def maybe_fileno(f):
    """Get object fileno, or :const:`None` if not defined."""
    ...

@contextmanager
def nested(*managers):
    """Nest context managers."""
    ...

