"""
This type stub file was generated by pyright.
"""

"""Object Utilities."""
class cached_property:
    """Cached property descriptor.

    Caches the return value of the get method on first call.

    Examples:
        .. code-block:: python

            @cached_property
            def connection(self):
                return Connection()

            @connection.setter  # Prepares stored value
            def connection(self, value):
                if value is None:
                    raise TypeError('Connection must be a connection')
                return value

            @connection.deleter
            def connection(self, value):
                # Additional action to do at del(self.attr)
                if value is not None:
                    print('Connection {0!r} deleted'.format(value)
    """
    def __init__(self, fget=..., fset=..., fdel=..., doc=...) -> None:
        ...
    
    def __get__(self, obj, type=...):
        ...
    
    def __set__(self, obj, value):
        ...
    
    def __delete__(self, obj, _sentinel=...):
        ...
    
    def setter(self, fset):
        ...
    
    def deleter(self, fdel):
        ...
    


