"""
This type stub file was generated by pyright.
"""

from typing import Iterator, Sequence, Tuple
from kombu import version_info_t

"""Text Utilities."""
def escape_regex(p: str, white: str = ...) -> str:
    """Escape string for use within a regular expression."""
    ...

def fmatch_iter(needle: str, haystack: Sequence[str], min_ratio: float = ...) -> Iterator[Tuple[float, str]]:
    """Fuzzy match: iteratively.

    Yields:
        Tuple: of ratio and key.
    """
    ...

def fmatch_best(needle: str, haystack: Sequence[str], min_ratio: float = ...) -> str:
    """Fuzzy match - Find best match (scalar)."""
    ...

def version_string_as_tuple(s: str) -> version_info_t:
    """Convert version string to version info tuple."""
    ...

