from .. import Provider as AddressProvider
from typing import Any

class Provider(AddressProvider):
    building_number_formats: Any = ...
    postcode_formats: Any = ...
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    cities: Any = ...
    countries: Any = ...
    states: Any = ...
    street_suffixes: Any = ...
    street_prefixes: Any = ...
    def street_prefix(self): ...
    def city_name(self): ...
    def state(self): ...
