from typing import Any

class ZoneinfoError(Exception): ...
class InvalidZoneinfoFile(ZoneinfoError): ...

class InvalidTimezone(ZoneinfoError):
    def __init__(self, name: Any) -> None: ...

class InvalidPosixSpec(ZoneinfoError):
    def __init__(self, spec: Any) -> None: ...
