from datetime import timedelta
from pendulum.utils._compat import PY2 as PY2, encode as encode
from typing import Any

class TransitionType:
    def __init__(self, offset: Any, is_dst: Any, abbr: Any) -> None: ...
    @property
    def offset(self) -> int: ...
    @property
    def abbreviation(self) -> str: ...
    def is_dst(self) -> bool: ...
    def utcoffset(self) -> timedelta: ...
