from tenacity import AttemptManager as AttemptManager, BaseRetrying as BaseRetrying, DoAttempt as DoAttempt, DoSleep as DoSleep, RetryCallState as RetryCallState
from typing import Any

class AsyncRetrying(BaseRetrying):
    sleep: Any = ...
    def __init__(self, sleep: Any = ..., **kwargs: Any) -> None: ...
    async def call(self, fn: Any, *args: Any, **kwargs: Any): ...
    def __aiter__(self): ...
    async def __anext__(self): ...
