from tenacity.compat import get_exc_info_from_future as get_exc_info_from_future
from typing import Any

def before_sleep_nothing(retry_state: Any) -> None: ...
def before_sleep_log(logger: Any, log_level: Any, exc_info: bool = ...): ...
