from ... import exc as exc, inspection as inspection, util as util
from ...orm import class_mapper as class_mapper, interfaces as interfaces
from ...orm.properties import ColumnProperty as ColumnProperty, RelationshipProperty as RelationshipProperty, SynonymProperty as SynonymProperty
from typing import Any, Optional

def add_class(classname: Any, cls: Any) -> None: ...

class _MultipleClassMarker:
    on_remove: Any = ...
    contents: Any = ...
    def __init__(self, classes: Any, on_remove: Optional[Any] = ...) -> None: ...
    def __iter__(self) -> Any: ...
    def attempt_get(self, path: Any, key: Any): ...
    def add_item(self, item: Any) -> None: ...

class _ModuleMarker:
    parent: Any = ...
    name: Any = ...
    contents: Any = ...
    mod_ns: Any = ...
    path: Any = ...
    def __init__(self, name: Any, parent: Any) -> None: ...
    def __contains__(self, name: Any): ...
    def __getitem__(self, name: Any): ...
    def resolve_attr(self, key: Any): ...
    def get_module(self, name: Any): ...
    def add_class(self, name: Any, cls: Any): ...

class _ModNS:
    def __init__(self, parent: Any) -> None: ...
    def __getattr__(self, key: Any): ...

class _GetColumns:
    cls: Any = ...
    def __init__(self, cls: Any) -> None: ...
    def __getattr__(self, key: Any): ...

class _GetTable:
    key: Any = ...
    metadata: Any = ...
    def __init__(self, key: Any, metadata: Any) -> None: ...
    def __getattr__(self, key: Any): ...

class _class_resolver:
    cls: Any = ...
    prop: Any = ...
    arg: Any = ...
    fallback: Any = ...
    def __init__(self, cls: Any, prop: Any, fallback: Any, arg: Any) -> None: ...
    def __call__(self): ...
