from ..en_PH import Provider as EnPhProvider
from typing import Any

class Provider(EnPhProvider):
    catch_phrase_formats: Any = ...
    noun_ish_good_traits: Any = ...
    good_service_adjectives: Any = ...
    objects_of_concern: Any = ...
    def random_noun_ish_good_trait(self): ...
    def random_good_service_adjective(self): ...
    def random_good_service_adjective_chain(self): ...
    def random_object_of_concern(self): ...
    def english_catch_phrase(self): ...
    def catch_phrase(self): ...
