from typing import Any

from .. import Provider as CompanyProvider

class Provider(CompanyProvider):
    formats: Any = ...
    company_prefixes: Any = ...
    company_suffixes: Any = ...
    large_companies: Any = ...
    def large_company(self): ...
    def company_prefix(self): ...
