import numpy as np
from pandas.core.construction import array as array
from pandas.core.dtypes.common import is_datetime64_dtype as is_datetime64_dtype, is_extension_array_dtype as is_extension_array_dtype, is_integer_dtype as is_integer_dtype, is_object_dtype as is_object_dtype, is_scalar as is_scalar, is_timedelta64_dtype as is_timedelta64_dtype
from pandas.core.dtypes.generic import ABCExtensionArray as ABCExtensionArray, ABCSeries as ABCSeries
from typing import Any, Union

def should_extension_dispatch(left: ABCSeries, right: Any) -> bool: ...
def should_series_dispatch(left: Any, right: Any, op: Any): ...
def dispatch_to_extension_op(op: Any, left: Union[ABCExtensionArray, np.ndarray], right: Any) -> Any: ...
