from typing import Any

def radd(left: Any, right: Any): ...
def rsub(left: Any, right: Any): ...
def rmul(left: Any, right: Any): ...
def rdiv(left: Any, right: Any): ...
def rtruediv(left: Any, right: Any): ...
def rfloordiv(left: Any, right: Any): ...
def rmod(left: Any, right: Any): ...
def rdivmod(left: Any, right: Any): ...
def rpow(left: Any, right: Any): ...
def rand_(left: Any, right: Any): ...
def ror_(left: Any, right: Any): ...
def rxor(left: Any, right: Any): ...
