from typing import Any

from .. import Provider as AutomotiveProvider

class Provider(AutomotiveProvider):
    LICENSE_FORMAT_EN: str = ...
    LICENSE_FORMAT_AR: str = ...
    PLATE_CHARS_EN: str = ...
    PLATE_CHARS_AR: str = ...
    PLATE_MAP: Any = ...
    def license_plate_en(self): ...
    def license_plate_ar(self): ...
    def license_plate(self): ...
