# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: win32comext, version: unspecified
# Module: win32comext.axscript.axscript, version: unspecified

'A module, encapsulating the ActiveX Scripting interfaces.'

import typing
import builtins as _mod_builtins
import win32.lib.pywintypes as _mod_pywintypes

_PyIID = _mod_pywintypes.IID

CATID_ActiveScript: _PyIID
CATID_ActiveScriptParse: _PyIID
IID_IActiveScript: _PyIID
IID_IActiveScriptError: _PyIID
IID_IActiveScriptParse: _PyIID
IID_IActiveScriptParseProcedure: _PyIID
IID_IActiveScriptSite: _PyIID
IID_IObjectSafety: _PyIID
IID_IProvideMultipleClassInfo: _PyIID
INTERFACESAFE_FOR_UNTRUSTED_CALLER: int
INTERFACESAFE_FOR_UNTRUSTED_DATA: int
INTERFACE_USES_DISPEX: int
INTERFACE_USES_SECURITY_MANAGER: int
MULTICLASSINFO_GETIIDPRIMARY: int
MULTICLASSINFO_GETIIDSOURCE: int
MULTICLASSINFO_GETNUMRESERVEDDISPIDS: int
MULTICLASSINFO_GETTYPEINFO: int
SCRIPTINFO_ALL_FLAGS: int
SCRIPTINFO_ITYPEINFO: int
SCRIPTINFO_IUNKNOWN: int
SCRIPTINTERRUPT_ALL_FLAGS: int
SCRIPTINTERRUPT_DEBUG: int
SCRIPTINTERRUPT_RAISEEXCEPTION: int
SCRIPTITEM_ALL_FLAGS: int
SCRIPTITEM_CODEONLY: int
SCRIPTITEM_GLOBALMEMBERS: int
SCRIPTITEM_ISPERSISTENT: int
SCRIPTITEM_ISSOURCE: int
SCRIPTITEM_ISVISIBLE: int
SCRIPTITEM_NOCODE: int
SCRIPTPROC_ALL_FLAGS: int
SCRIPTPROC_HOSTMANAGESSOURCE: int
SCRIPTPROC_IMPLICIT_PARENTS: int
SCRIPTPROC_IMPLICIT_THIS: int
SCRIPTSTATE_CLOSED: int
SCRIPTSTATE_CONNECTED: int
SCRIPTSTATE_DISCONNECTED: int
SCRIPTSTATE_INITIALIZED: int
SCRIPTSTATE_STARTED: int
SCRIPTSTATE_UNINITIALIZED: int
SCRIPTTEXT_ALL_FLAGS: int
SCRIPTTEXT_ISEXPRESSION: int
SCRIPTTEXT_ISPERSISTENT: int
SCRIPTTEXT_ISVISIBLE: int
SCRIPTTHREADSTATE_NOTINSCRIPT: int
SCRIPTTHREADSTATE_RUNNING: int
SCRIPTTYPELIB_ISCONTROL: int
SCRIPTTYPELIB_ISPERSISTENT: int
SCRIPT_E_REPORTED: int
TIFLAGS_EXTENDDISPATCHONLY: int
__doc__: str
__file__: str
__name__: str
__package__: str
def __getattr__(name) -> typing.Any:
    ...

