from typing import Mapping

from ...classes.graph import Graph

__all__ = [
    "is_bipartite",
    "is_bipartite_node_set",
    "color",
    "sets",
    "density",
    "degrees",
]

def color(G: Graph) -> Mapping: ...
def is_bipartite(G: Graph): ...
def is_bipartite_node_set(G: Graph, nodes): ...
def sets(G: Graph, top_nodes=None) -> tuple[set, set]: ...
def density(B, nodes) -> float: ...
def degrees(B, nodes, weight=None) -> tuple[dict, ...]: ...
