import numpy as np

def set_bitset_memoryview(bitset: np.ndarray, val: np.uint8) -> None: ...
def set_raw_bitset_from_binned_bitset(raw_bitset: np.ndarray, binned_bitset: np.ndarray, categories: np.ndarray) -> None: ...
