import contextlib

__all__ = ["use", "context", "available", "library", "reload_library"]

class __getattr__:
    STYLE_FILE_PATTERN = ...

BASE_LIBRARY_PATH = ...
USER_LIBRARY_PATHS = ...
STYLE_EXTENSION = ...
STYLE_BLACKLIST = ...

def use(style: str) -> None: ...
@contextlib.contextmanager
def context(style: str, after_reset: bool = ...): ...
def load_base_library() -> dict: ...
def iter_user_libraries(): ...
def update_user_library(library): ...
def read_style_directory(
    style_dir: str,
) -> dict: ...
def update_nested_dict(main_dict: dict, new_dict: dict): ...

library = ...
available = ...

def reload_library() -> None: ...
