import datetime
import numpy as np
from typing import Any, Callable, Iterable, Literal, Sequence
from matplotlib._typing import *
from matplotlib.path import Path

"""
This type stub file was generated by pyright.
"""
from typing import Any, Dict, Iterator

import contextlib
from matplotlib import _api, _docstring

"""
Core functions and attributes for the matplotlib style library:

``use``
    Select style sheet to override the current matplotlib settings.
``context``
    Context manager to use a style sheet temporarily.
``available``
    List available style sheets.
``library``
    A dictionary of style names and matplotlib settings.
"""

__all__ = ["use", "context", "available", "library", "reload_library"]

class __getattr__:
    STYLE_FILE_PATTERN = ...

BASE_LIBRARY_PATH = ...
USER_LIBRARY_PATHS = ...
STYLE_EXTENSION = ...
STYLE_BLACKLIST = ...

def use(style: str) -> None:  # -> None:
    """
    Use Matplotlib style settings from a style specification.

    The style name of 'default' is reserved for reverting back to
    the default style settings.

    .. note::

       This updates the `.rcParams` with the settings from the style.
       `.rcParams` not defined in the style are kept.

    Parameters
    ----------
    style : str, dict, Path or list
        A style specification. Valid options are:

        +------+-------------------------------------------------------------+
        | str  | The name of a style or a path/URL to a style file. For a    |
        |      | list of available style names, see `.style.available`.      |
        +------+-------------------------------------------------------------+
        | dict | Dictionary with valid key/value pairs for                   |
        |      | `matplotlib.rcParams`.                                      |
        +------+-------------------------------------------------------------+
        | Path | A path-like object which is a path to a style file.         |
        +------+-------------------------------------------------------------+
        | list | A list of style specifiers (str, Path or dict) applied from |
        |      | first to last in the list.                                  |
        +------+-------------------------------------------------------------+

    Notes
    -----
    The following `.rcParams` are not related to style and will be ignored if
    found in a style specification:

    %s
    """
    ...

@contextlib.contextmanager
def context(
    style: str, after_reset: bool = ...
) -> Iterator[None]:  # -> Generator[None, None, None]:
    """
    Context manager for using style settings temporarily.

    Parameters
    ----------
    style : str, dict, Path or list
        A style specification. Valid options are:

        +------+-------------------------------------------------------------+
        | str  | The name of a style or a path/URL to a style file. For a    |
        |      | list of available style names, see `.style.available`.      |
        +------+-------------------------------------------------------------+
        | dict | Dictionary with valid key/value pairs for                   |
        |      | `matplotlib.rcParams`.                                      |
        +------+-------------------------------------------------------------+
        | Path | A path-like object which is a path to a style file.         |
        +------+-------------------------------------------------------------+
        | list | A list of style specifiers (str, Path or dict) applied from |
        |      | first to last in the list.                                  |
        +------+-------------------------------------------------------------+

    after_reset : bool
        If True, apply style after resetting settings to their defaults;
        otherwise, apply style on top of the current settings.
    """
    ...

def load_base_library():  # -> dict[Unknown, Unknown]:
    """Load style library defined in this package."""
    ...

def iter_user_libraries(): ...
def update_user_library(library):
    """Update style library with user-defined rc files."""
    ...

def read_style_directory(
    style_dir: str,
) -> Dict[Any, Any]:  # -> dict[Unknown, Unknown]:
    """Return dictionary of styles defined in *style_dir*."""
    ...

def update_nested_dict(main_dict, new_dict):
    """
    Update nested dict (only level of nesting) with new values.

    Unlike `dict.update`, this assumes that the values of the parent dict are
    dicts (or dict-like), so you shouldn't replace the nested dict if it
    already exists. Instead you should update the sub-dict.
    """
    ...

library = ...
available = ...

def reload_library() -> None:  # -> None:
    """Reload the style library."""
    ...
