from .. import Provider as AddressProvider
from typing import Any

class Provider(AddressProvider):
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    building_number_formats: Any = ...
    postcode_formats: Any = ...
    cities: Any = ...
    states: Any = ...
    countries: Any = ...
    def city_name(self): ...
    def state(self): ...
