from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    building_number_formats: Any = ...
    street_suffixes: Any = ...
    postcode_formats: Any = ...
    city_formats: Any = ...
    countries: Any = ...
    cities: Any = ...
    provinces: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    def province(self): ...
    def city(self): ...
