import datetime
import numpy as np
from typing import Any, Callable, Iterable, Literal, Sequence
from matplotlib._typing import *
from matplotlib.gridspec import SubplotSpec
from matplotlib.figure import Figure
from matplotlib.axes import Axes

"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""

class SubplotBase:
    """
    Base class for subplots, which are :class:`Axes` instances with
    additional methods to facilitate generating and manipulating a set
    of :class:`Axes` within a figure.
    """

    def __init__(self, fig, *args, **kwargs) -> None:
        """
        Parameters
        ----------
        fig : `Figure`

        *args : tuple (*nrows*, *ncols*, *index*) or int
            The array of subplots in the figure has dimensions ``(nrows,
            ncols)``, and *index* is the index of the subplot being created.
            *index* starts at 1 in the upper left corner and increases to the
            right.

            If *nrows*, *ncols*, and *index* are all single digit numbers, then
            *args* can be passed as a single 3-digit number (e.g. 234 for
            (2, 3, 4)).

        **kwargs
            Keyword arguments are passed to the Axes (sub)class constructor.
        """
        ...
    def get_subplotspec(self):
        """Return the `.SubplotSpec` instance associated with the subplot."""
        ...
    def set_subplotspec(self, subplotspec):
        """Set the `.SubplotSpec`. instance associated with the subplot."""
        ...
    def get_gridspec(self):
        """Return the `.GridSpec` instance associated with the subplot."""
        ...
    def label_outer(self):
        """
        Only show "outer" labels and tick labels.

        x-labels are only kept for subplots on the last row (or first row, if
        labels are on the top side); y-labels only for subplots on the first
        column (or last column, if labels are on the right side).
        """
        ...

subplot_class_factory = ...
Subplot = ...
