from typing import Any

from ... import BaseProvider as BaseProvider

class Provider(BaseProvider):
    protocol_licenses: Any = ...
    motorcycle_license_formats: Any = ...
    automobile_license_formats: Any = ...
    license_formats: Any = ...
    def protocol_license_plate(self): ...
    def motorcycle_license_plate(self): ...
    def automobile_license_plate(self): ...
    def license_plate(self): ...
