from datetime import date as real_date, datetime as real_datetime
from typing import Any

class date(real_date):
    def strftime(self, fmt: Any): ...

class datetime(real_datetime):
    def strftime(self, fmt: Any): ...
    def combine(self, date: Any, time: Any): ...
    def date(self): ...

def new_date(d: Any): ...
def new_datetime(d: Any): ...
def strftime(dt: Any, fmt: Any): ...
