from typing import Any, Callable, TypeVar

from faker.utils import text as text

_T = TypeVar("_T")

def slugify(fn: Callable[..., _T]) -> Callable[..., _T]: ...
def slugify_domain(fn: Callable[..., _T]) -> Callable[..., _T]: ...
def slugify_unicode(fn: Callable[..., _T]) -> Callable[..., _T]: ...
def lowercase(fn: Callable[..., _T]) -> Callable[..., _T]: ...
