from typing import Any, Optional

def random_sample(random: Optional[Any] = ...): ...
def cumsum(it: Any) -> None: ...
def choices_distribution_unique(
    a: Any, p: Any, random: Optional[Any] = ..., length: int = ...
): ...
def choices_distribution(
    a: Any, p: Any, random: Optional[Any] = ..., length: int = ...
): ...
