from types import ModuleType
from typing import Any, Sequence

def get_path(module: ModuleType) -> str: ...
def list_module(module: ModuleType) -> Sequence[str]: ...
def find_available_locales(providers: Sequence[str]) -> Sequence[str]: ...
def find_available_providers(modules: Sequence[str]) -> Sequence[str]: ...
