from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    city_suffixes: Any = ...
    street_suffixes: Any = ...
    region_suffixes: Any = ...
    city_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    postcode_formats: Any = ...
    building_number_formats: Any = ...
    city_prefixes: Any = ...
    street_suffixes_masc: Any = ...
    street_suffixes_fem: Any = ...
    street_suffixes_neu: Any = ...
    street_titles: Any = ...
    street_titles_noflex: Any = ...
    street_titles_irregular_masc: Any = ...
    street_titles_irregular_neu: Any = ...
    city_names: Any = ...
    region_republics: Any = ...
    region_krai: Any = ...
    region_oblast: Any = ...
    region_ao: Any = ...
    countries: Any = ...
    def city_prefix(self): ...
    def city_name(self): ...
    def country(self): ...
    def region(self): ...
    def street_suffix(self): ...
    def street_title(self): ...
    def street_name(self): ...
