from typing import Any

from .. import Provider as BaseProvider

class Provider(BaseProvider):
    INVALID_SSN_TYPE: str = ...
    SSN_TYPE: str = ...
    ITIN_TYPE: str = ...
    EIN_TYPE: str = ...
    def itin(self): ...
    def ein(self): ...
    def invalid_ssn(self): ...
    def ssn(self, taxpayer_identification_number_type: Any = ...): ...
