from typing import Any

_name_with_digits_p = ...
def split_super_sub(text) -> tuple[Any, list[Any], list[Any]] | tuple[Any | None, list[Any], list[Any]]:
    ...

def requires_partial(expr) -> bool:
    ...

