from typing import Any

from sympy.printing.codeprinter import CodePrinter

known_functions = ...

class FCodePrinter(CodePrinter):
    printmethod = ...
    language = ...
    type_aliases = ...
    type_mappings = ...
    type_modules = ...
    _default_settings: dict[str, Any] = ...
    _operators = ...
    _relationals = ...
    def __init__(self, settings=...) -> None: ...
    def indent_code(self, code) -> str | list[Any]: ...
