from typing import Any
from sympy.printing.codeprinter import CodePrinter

known_fcns_src1 = ...
known_fcns_src2 = ...
class JuliaCodePrinter(CodePrinter):
    printmethod = ...
    language = ...
    _operators = ...
    _default_settings: dict[str, Any] = ...
    def __init__(self, settings=...) -> None:
        ...
    
    _print_Tuple = ...
    def indent_code(self, code) -> str | list[Any]:
        ...
    


def julia_code(expr, assign_to=..., **settings) -> str | tuple[set[tuple[Any, str]], set[Any], str]:
    ...

def print_julia_code(expr, **settings) -> None:
    ...

