from typing import Any, Callable

from sympy.printing.printer import Printer, print_function

accepted_latex_functions = ...
tex_greek_dictionary = ...
other_symbols = ...
modifier_dict: dict[str, Callable[[str], str]] = ...
greek_letters_set = ...
_between_two_numbers_p = ...

def latex_escape(s: str) -> str: ...

class LatexPrinter(Printer):
    printmethod = ...
    _default_settings: dict[str, Any] = ...
    def __init__(self, settings=...) -> None: ...
    def parenthesize(self, item, level, is_neg=..., strict=...) -> str: ...
    def parenthesize_super(self, s) -> str: ...
    def doprint(self, expr) -> str: ...

    _print_BooleanTrue = ...
    _print_BooleanFalse = ...
    _print_Max = ...
    _print_gamma = ...
    _print_RandomSymbol = ...
    _print_frozenset = ...
    _print_SeqPer = ...
    _print_SeqAdd = ...
    _print_SeqMul = ...
    _print_IDFT = ...
    def emptyPrinter(self, expr) -> str: ...

def translate(s: str) -> str: ...
@print_function(LatexPrinter)
def latex(expr, **settings) -> str: ...
def print_latex(expr, **settings) -> None: ...
def multiline_latex(lhs, rhs, terms_per_line=..., environment=..., use_dots=..., **settings) -> str: ...
