from typing import Any
from sympy.printing.codeprinter import CodePrinter

_known_func_same_name = ...
known_functions = ...
number_symbols = ...
spec_relational_ops = ...
not_supported_symbol = ...
class MapleCodePrinter(CodePrinter):
    printmethod = ...
    language = ...
    _default_settings = ...
    def __init__(self, settings=...) -> None:
        ...
    


def maple_code(expr, assign_to=..., **settings) -> str | tuple[set[tuple[Any, str]], set[Any], str]:
    ...

def print_maple_code(expr, **settings) -> None:
    ...

