from sympy.printing.pycode import ArrayPrinter, PythonCodePrinter

_not_in_numpy = ...
_in_numpy = ...
_known_functions_numpy = ...
_known_constants_numpy = ...
_numpy_known_functions = ...
_numpy_known_constants = ...

class NumPyPrinter(ArrayPrinter, PythonCodePrinter):
    _module = ...
    _kf = ...
    _kc = ...
    def __init__(self, settings=...) -> None: ...

    _add = ...
    _einsum = ...
    _transpose = ...
    _ones = ...
    _zeros = ...
    _print_lowergamma = ...
    _print_uppergamma = ...
    _print_fresnelc = ...
    _print_fresnels = ...

_known_functions_scipy_special = ...
_known_constants_scipy_constants = ...
_scipy_known_functions = ...
_scipy_known_constants = ...

class SciPyPrinter(NumPyPrinter):
    _kf = ...
    _kc = ...
    def __init__(self, settings=...) -> None: ...

    _print_ImmutableSparseMatrix = ...

_cupy_known_functions = ...
_cupy_known_constants = ...

class CuPyPrinter(NumPyPrinter):
    _module = ...
    _kf = ...
    _kc = ...
    def __init__(self, settings=...) -> None: ...

_jax_known_functions = ...
_jax_known_constants = ...

class JaxPrinter(NumPyPrinter):
    _module = ...
    _kf = ...
    _kc = ...
    def __init__(self, settings=...) -> None: ...
