PRECEDENCE = ...
PRECEDENCE_VALUES = ...

def precedence_Mul(item) -> int: ...
def precedence_Rational(item) -> int: ...
def precedence_Integer(item) -> int: ...
def precedence_Float(item) -> int: ...
def precedence_PolyElement(item) -> int: ...
def precedence_FracElement(item) -> int: ...
def precedence_UnevaluatedExpr(item) -> float: ...

PRECEDENCE_FUNCTIONS = ...

def precedence(item) -> int: ...

PRECEDENCE_TRADITIONAL = ...

def precedence_traditional(item) -> int: ...
