from typing import Any
from sympy.printing.codeprinter import CodePrinter

_kw = ...
_known_functions = ...
_known_functions_math = ...
_known_constants_math = ...
class AbstractPythonCodePrinter(CodePrinter):
    printmethod = ...
    language = ...
    reserved_words = ...
    modules = ...
    tab = ...
    _kf = ...
    _kc = ...
    _operators = ...
    _default_settings = ...
    def __init__(self, settings=...) -> None:
        ...
    
    _print_ImmutableDenseMatrix = ...


class ArrayPrinter:
    ...


class PythonCodePrinter(AbstractPythonCodePrinter):
    _print_lowergamma = ...
    _print_uppergamma = ...
    _print_fresnelc = ...
    _print_fresnels = ...


def pycode(expr, **settings) -> str | tuple[set[tuple[Any, str]], set[Any], str]:
    ...

_not_in_mpmath = ...
_in_mpmath = ...
_known_functions_mpmath = ...
_known_constants_mpmath = ...
class MpmathPrinter(PythonCodePrinter):
    printmethod = ...
    language = ...
    _kf = ...
    _kc = ...


class SymPyPrinter(AbstractPythonCodePrinter):
    language = ...


