from sympy.matrices import Matrix

class TableForm:
    def __init__(self, data, **kwarg) -> None: ...
    def __repr__(self): ...
    def __str__(self) -> str: ...
    def as_matrix(self) -> Matrix: ...
    def as_str(self) -> str: ...
    def as_latex(self): ...
