from typing import Any
from sympy.printing.pycode import AbstractPythonCodePrinter, ArrayPrinter

tensorflow = ...
class TensorflowPrinter(ArrayPrinter, AbstractPythonCodePrinter):
    printmethod = ...
    mapping = ...
    _default_settings = ...
    def __init__(self, settings=...) -> None:
        ...
    
    _print_Expr = ...
    _print_Application = ...
    _print_MatrixExpr = ...
    _print_Relational = ...
    _print_Not = ...
    _print_And = ...
    _print_Or = ...
    _print_HadamardProduct = ...
    _print_Trace = ...
    _print_Determinant = ...
    _module = ...
    _einsum = ...
    _add = ...
    _transpose = ...
    _ones = ...
    _zeros = ...


def tensorflow_code(expr, **settings) -> str | tuple[set[tuple[Any, str]], set[Any], str]:
    ...

