from .. import Provider as CompanyProvider
from typing import Any

class Provider(CompanyProvider):
    formats: Any = ...
    company_prefixes: Any = ...
    company_categories: Any = ...
    def company_prefix(self): ...
    def company_category(self): ...
