from typing import Any

from .. import Provider as PersonProvider

class Provider(PersonProvider):
    formats_female: Any = ...
    formats_male: Any = ...
    formats: Any = ...
    first_names_female: Any = ...
    first_names_male: Any = ...
    first_names: Any = ...
    last_names: Any = ...
    kana_formats: Any = ...
    first_kana_names_female: Any = ...
    first_kana_names_male: Any = ...
    first_kana_names: Any = ...
    last_kana_names: Any = ...
    romanized_formats: Any = ...
    first_romanized_names_female: Any = ...
    first_romanized_names_male: Any = ...
    first_romanized_names: Any = ...
    last_romanized_names: Any = ...
    def kana_name(self): ...
    def first_kana_name(self): ...
    def first_kana_name_female(self): ...
    def first_kana_name_male(self): ...
    def last_kana_name(self): ...
    def romanized_name(self): ...
    def first_romanized_name(self): ...
    def first_romanized_name_female(self): ...
    def first_romanized_name_male(self): ...
    def last_romanized_name(self): ...
