# -----------------------------------------------------------------------------
# Copyright (c) 2014, Nicolas P. Rougier
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
# -----------------------------------------------------------------------------

class Number:
    def __init__(self, content): ...
    def __float__(self): ...
    @property
    def value(self): ...
    def __repr__(self): ...
