# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------
# Copyright (c) 2014, Nicolas P. Rougier. All rights reserved.
# Distributed under the terms of the new BSD License.
# -----------------------------------------------------------------------------

from .length import XLength, YLength

class Viewport(object):
    def __init__(self, content=None, parent=None): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    def __repr__(self): ...
    @property
    def xml(self): ...
    @property
    def _xml(self, prefix=""): ...
