from ... import sql as sql, util as util
from .base import MySQLCompiler as MySQLCompiler, MySQLDialect as MySQLDialect, MySQLExecutionContext as MySQLExecutionContext, MySQLIdentifierPreparer as MySQLIdentifierPreparer, TEXT as TEXT
from typing import Any, Optional

class MySQLExecutionContext_mysqldb(MySQLExecutionContext):
    @property
    def rowcount(self): ...

class MySQLCompiler_mysqldb(MySQLCompiler): ...
class MySQLIdentifierPreparer_mysqldb(MySQLIdentifierPreparer): ...

class MySQLDialect_mysqldb(MySQLDialect):
    driver: str = ...
    supports_unicode_statements: bool = ...
    supports_sane_rowcount: bool = ...
    supports_sane_multi_rowcount: bool = ...
    supports_native_decimal: bool = ...
    default_paramstyle: str = ...
    execution_ctx_cls: Any = ...
    statement_compiler: Any = ...
    preparer: Any = ...
    server_side_cursors: Any = ...
    def __init__(self, server_side_cursors: bool = ..., **kwargs: Any) -> None: ...
    def supports_server_side_cursors(self): ...
    @classmethod
    def dbapi(cls): ...
    def on_connect(self): ...
    def do_ping(self, dbapi_connection: Any): ...
    def do_executemany(self, cursor: Any, statement: Any, parameters: Any, context: Optional[Any] = ...) -> None: ...
    def create_connect_args(self, url: Any): ...
dialect = MySQLDialect_mysqldb
