from ...util import langhelpers as langhelpers, py3k as py3k
from .mysqldb import MySQLDialect_mysqldb as MySQLDialect_mysqldb
from typing import Any

class MySQLDialect_pymysql(MySQLDialect_mysqldb):
    driver: str = ...
    description_encoding: Any = ...
    supports_unicode_statements: bool = ...
    supports_unicode_binds: bool = ...
    server_side_cursors: Any = ...
    def __init__(self, server_side_cursors: bool = ..., **kwargs: Any) -> None: ...
    def supports_server_side_cursors(self): ...
    @classmethod
    def dbapi(cls): ...
    def is_disconnect(self, e: Any, connection: Any, cursor: Any): ...
dialect = MySQLDialect_pymysql
