from ... import util as util
from ...connectors.pyodbc import PyODBCConnector as PyODBCConnector
from ...sql.sqltypes import Time as Time
from .base import MySQLDialect as MySQLDialect, MySQLExecutionContext as MySQLExecutionContext
from .types import TIME as TIME
from typing import Any

class _pyodbcTIME(TIME):
    def result_processor(self, dialect: Any, coltype: Any): ...

class MySQLExecutionContext_pyodbc(MySQLExecutionContext):
    def get_lastrowid(self): ...

class MySQLDialect_pyodbc(PyODBCConnector, MySQLDialect):
    colspecs: Any = ...
    supports_unicode_statements: bool = ...
    execution_ctx_cls: Any = ...
    pyodbc_driver_name: str = ...
    def __init__(self, **kw: Any) -> None: ...
dialect = MySQLDialect_pyodbc
