from ... import engine as engine
from ...connectors.zxJDBC import ZxJDBCConnector as ZxJDBCConnector
from .base import MSDialect as MSDialect, MSExecutionContext as MSExecutionContext
from typing import Any

class MSExecutionContext_zxjdbc(MSExecutionContext):
    def pre_exec(self) -> None: ...
    def post_exec(self) -> None: ...

class MSDialect_zxjdbc(ZxJDBCConnector, MSDialect):
    jdbc_db_name: str = ...
    jdbc_driver_name: str = ...
    execution_ctx_cls: Any = ...
dialect = MSDialect_zxjdbc
