import numpy as np
from matplotlib._typing import *
from matplotlib.text import Text
from matplotlib.font_manager import FontProperties
from io import BufferedWriter, BytesIO
from matplotlib.font_manager import FontProperties
from typing import Tuple, Union

import threading
from matplotlib.backend_bases import (
    FigureCanvasBase,
    FigureManagerBase,
    GraphicsContextBase,
    RendererBase,
    _Backend,
)

backend_version = ...

def get_hinting_flag() -> int: ...

class RendererAgg(RendererBase):

    lock: threading.RLock
    def __init__(self, width, height, dpi) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    def draw_path(self, gc, path, transform, rgbFace=...): ...
    def draw_mathtext(self, gc, x, y, s, prop, angle): ...
    def draw_text(
        self,
        gc: GraphicsContextBase,
        x: float,
        y: float,
        s: str,
        prop: FontProperties,
        angle: float,
        ismath=...,
        mtext: Text = ...,
    ): ...
    def get_text_width_height_descent(
        self, s: str, prop: FontProperties, ismath: Union[bool, str]
    ) -> Tuple[float, float, float]: ...
    def draw_tex(self, gc, x, y, s, prop, angle, *, mtext=...): ...
    def get_canvas_width_height(self): ...
    def points_to_pixels(self, points: Union[int, float]) -> float: ...
    def buffer_rgba(self) -> memoryview: ...
    def tostring_argb(self): ...
    def tostring_rgb(self): ...
    def clear(self) -> None: ...
    def option_image_nocomposite(self) -> bool: ...
    def option_scale_image(self) -> bool: ...
    def restore_region(self, region, bbox=..., xy=...): ...
    def start_filter(self) -> None: ...
    def stop_filter(self, post_processing): ...

class FigureCanvasAgg(FigureCanvasBase):
    def copy_from_bbox(self, bbox): ...
    def restore_region(self, region, bbox=..., xy=...): ...
    def draw(self) -> None: ...
    def get_renderer(self, cleared: bool = ...) -> RendererAgg: ...
    def tostring_rgb(self) -> str: ...
    def tostring_argb(self) -> np.str_: ...
    def buffer_rgba(self) -> memoryview: ...
    def print_raw(self, filename_or_obj, *args): ...

    print_rgba = ...

    def print_png(
        self,
        filename_or_obj: Union[BytesIO, BufferedWriter, str],
        *args,
        metadata: dict = ...,
        pil_kwargs: dict = ...
    ) -> None: ...
    def print_to_buffer(self): ...
    def print_jpg(
        self, filename_or_obj: str | PathLike | FileLike, *args, pil_kwargs: dict = ...
    ): ...

    print_jpeg = ...
    def print_tif(
        self, filename_or_obj: str | PathLike | FileLike, *, pil_kwargs: dict = ...
    ): ...

    print_tiff = ...
    def print_webp(
        self, filename_or_obj: str | PathLike | FileLike, *, pil_kwargs: dict = ...
    ): ...

class _BackendAgg(_Backend):
    FigureCanvas = FigureCanvasAgg
    FigureManager = FigureManagerBase
