import numpy as np
from io import BytesIO
from enum import Enum
from functools import total_ordering
from typing import Any, Optional, Set

from matplotlib._typing import *
from matplotlib.text import Text
from matplotlib._enums import CapStyle, JoinStyle
from matplotlib.font_manager import FontProperties
from matplotlib.figure import Figure
from matplotlib.transforms import Affine2DBase, Transform
from matplotlib.backend_bases import (
    FigureCanvasBase,
    FigureManagerBase,
    GraphicsContextBase,
    _Backend,
)
from . import _backend_pdf_ps

def fill(strings, linelen=...): ...
def pdfRepr(obj) -> bytes: ...

class Reference:
    def __init__(self, id: int) -> None: ...
    def __repr__(self): ...
    def pdfRepr(self) -> bytes: ...
    def write(self, contentsy, file: "PdfFile") -> None: ...

@total_ordering
class Name:
    def __init__(self, name: bytes | Name | str) -> None: ...
    def __repr__(self): ...
    def __str__(self) -> str: ...
    def __eq__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    @staticmethod
    def hexify(match): ...
    def pdfRepr(self) -> bytes: ...

class Operator:
    def __init__(self, op) -> None: ...
    def __repr__(self): ...
    def pdfRepr(self): ...

class Verbatim:
    """Store verbatim PDF command content for later inclusion in the stream."""

    def __init__(self, x: bytes) -> None: ...
    def pdfRepr(self) -> bytes: ...

class Op(Enum):
    """PDF operators (not an exhaustive list)."""

    close_fill_stroke = ...
    fill_stroke = ...
    fill = ...
    closepath = ...
    close_stroke = ...
    stroke = ...
    endpath = ...
    begin_text = ...
    end_text = ...
    curveto = ...
    rectangle = ...
    lineto = ...
    moveto = ...
    concat_matrix = ...
    use_xobject = ...
    setgray_stroke = ...
    setgray_nonstroke = ...
    setrgb_stroke = ...
    setrgb_nonstroke = ...
    setcolorspace_stroke = ...
    setcolorspace_nonstroke = ...
    setcolor_stroke = ...
    setcolor_nonstroke = ...
    setdash = ...
    setlinejoin = ...
    setlinecap = ...
    setgstate = ...
    gsave = ...
    grestore = ...
    textpos = ...
    selectfont = ...
    textmatrix = ...
    show = ...
    showkern = ...
    setlinewidth = ...
    clip = ...
    shading = ...
    op = ...
    def pdfRepr(self) -> bytes: ...
    @classmethod
    def paint_path(cls, fill: bool, stroke: bool) -> "Op": ...

class Stream:
    def __init__(
        self,
        id: int,
        len: Reference | None,
        file: "PdfFile",
        extra: None
        | dict[str, int | Name]
        | dict[str, Name | list[int]]
        | dict[str, Name | int | Verbatim]
        | dict[str, Name | int | Verbatim | Reference] = ...,
        png: None | dict[str, int] = ...,
    ) -> None: ...
    def end(self) -> None: ...
    def write(self, data: bytes) -> None: ...

class PdfFile:
    def __init__(
        self, filename: BytesIO | str, metadata: dict[str, Any] = ...
    ) -> None: ...
    def newPage(self, width, height): ...
    def newTextnote(self, text: str, positionRect: list[int] = ...) -> None: ...
    def finalize(self) -> None: ...
    def close(self) -> None: ...
    def write(self, data: bytes) -> None: ...
    def output(self, *data) -> None: ...
    def beginStream(
        self,
        id: int,
        len: None | Reference,
        extra: None
        | dict[str, int | Name]
        | dict[str, Name | list[int]]
        | dict[str, Name | int | Verbatim]
        | dict[str, Name | int | Verbatim | Reference] = ...,
        png: Optional[dict[str, int]] = ...,
    ) -> None: ...
    def endStream(self) -> None: ...
    def outputStream(self, ref: Reference, data: bytes, *, extra=...) -> None: ...
    def fontName(self, fontprop: FontProperties | str) -> Name: ...
    def dviFontName(self, dvifont): ...
    def writeFonts(self) -> None: ...
    def createType1Descriptor(self, t1font, fontfile): ...
    def embedTTF(self, filename: str, characters: Set[int]) -> Reference: ...
    def alphaState(self, alpha: tuple[float, float]) -> Name: ...
    def writeExtGSTates(self) -> None: ...
    def hatchPattern(self, hatch_style): ...
    def writeHatches(self) -> None: ...
    def addGouraudTriangles(
        self, points: np.ndarray, colors: np.ndarray
    ) -> tuple[Name, Reference]: ...
    def writeGouraudTriangles(self) -> None: ...
    def imageObject(self, image) -> Name: ...
    def writeImages(self) -> None: ...
    def markerObject(
        self, path, trans, fill, stroke, lw, joinstyle, capstyle
    ) -> Name: ...
    def writeMarkers(self) -> None: ...
    def pathCollectionObject(self, gc, path, trans, padding, filled, stroked): ...
    def writePathCollectionTemplates(self) -> None: ...
    @staticmethod
    def pathOperations(path, transform, clip=..., simplify=..., sketch=...): ...
    def writePath(self, path, transform, clip=..., sketch=...): ...
    def reserveObject(self, name: str = ...) -> Reference: ...
    def recordXref(self, id: int) -> None: ...
    def writeObject(self, object: Reference, contents: Any) -> None: ...
    def writeXref(self) -> None: ...
    def writeInfoDict(self) -> None: ...
    def writeTrailer(self) -> None: ...

class RendererPdf(_backend_pdf_ps.RendererPDFPSBase):
    def __init__(self, file, image_dpi, height, width) -> None: ...
    def finalize(self) -> None: ...
    def check_gc(
        self,
        gc: "GraphicsContextPdf",
        fillcolor: None | tuple[float, float, float, float] = ...,
    ) -> None: ...
    def get_image_magnification(self): ...
    def draw_image(
        self,
        gc: GraphicsContextBase,
        x: Scalar,
        y: Scalar,
        im,
        transform: Affine2DBase = ...,
    ): ...
    def draw_path(self, gc, path, transform, rgbFace=...): ...
    def draw_path_collection(
        self,
        gc,
        master_transform,
        paths,
        all_transforms,
        offsets,
        offsetTrans,
        facecolors,
        edgecolors,
        linewidths,
        linestyles,
        antialiaseds,
        urls,
        offset_position,
    ): ...
    def draw_markers(
        self,
        gc: GraphicsContextBase,
        marker_path,
        marker_trans: Transform,
        path,
        trans: Transform,
        rgbFace=...,
    ): ...
    def draw_gouraud_triangle(self, gc: GraphicsContextBase, points, colors, trans): ...
    def draw_gouraud_triangles(self, gc, points, colors, trans): ...
    def draw_mathtext(self, gc, x, y, s, prop, angle): ...
    def draw_tex(self, gc, x, y, s, prop, angle, *, mtext=...): ...
    def encode_string(self, s: str, fonttype: int) -> bytes: ...
    def draw_text(
        self,
        gc: GraphicsContextBase,
        x: float,
        y: float,
        s: str,
        prop: FontProperties,
        angle: float,
        ismath=...,
        mtext: Text = ...,
    ): ...
    def new_gc(self) -> "GraphicsContextPdf": ...

class GraphicsContextPdf(GraphicsContextBase):
    def __init__(self, file: PdfFile) -> None: ...
    def __repr__(self): ...
    def stroke(self) -> bool: ...
    def fill(self, *args) -> bool: ...
    def paint(
        self,
    ) -> Op: ...
    capstyles = ...
    joinstyles = ...
    def capstyle_cmd(self, style: CapStyle) -> list[int | Op]: ...
    def joinstyle_cmd(self, style: JoinStyle) -> list[int | Op]: ...
    def linewidth_cmd(self, width: int | float) -> list[float | Op]: ...
    def dash_cmd(self, dashes): ...
    def alpha_cmd(
        self, alpha: float, forced: bool, effective_alphas: tuple[float, float]
    ) -> list[Name | Op]: ...
    def hatch_cmd(
        self, hatch: None, hatch_color: tuple[float, float, float, float]
    ) -> list[Name | Op | float]: ...
    def rgb_cmd(
        self,
        rgb: tuple[float, float, float, float],
    ) -> list[float | Op]: ...
    def fillcolor_cmd(
        self,
        rgb: None | tuple[float, float, float, float],
    ) -> list[float | Op]: ...
    def push(self) -> list[Op]: ...
    def pop(self) -> list[Op]: ...
    def clip_cmd(self, cliprect, clippath) -> list[Op]: ...
    commands = ...
    def delta(self, other: "GraphicsContextPdf") -> list[Op | Name | float]: ...
    def copy_properties(self, other: GraphicsContextPdf) -> None: ...
    def finalize(self) -> list[Op]: ...

class PdfPages:
    def __init__(
        self, filename: str, keep_empty: bool = ..., metadata: dict[str, Any] = ...
    ) -> None: ...
    def __enter__(self) -> "PdfPages": ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def close(self) -> None: ...
    def infodict(self) -> dict[str, Any]: ...
    def savefig(self, figure: Figure | int = ..., **kwargs) -> None: ...
    def get_pagecount(self) -> int: ...
    def attach_note(self, text: str, positionRect: list[int] = ...) -> None: ...

class FigureCanvasPdf(FigureCanvasBase):
    fixed_dpi = ...
    filetypes = ...
    def get_default_filetype(self): ...
    def print_pdf(
        self,
        filename: BytesIO | PdfPages | str,
        *,
        bbox_inches_restore=...,
        metadata=...
    ) -> None: ...
    def draw(self): ...

FigureManagerPdf = FigureManagerBase

class _BackendPdf(_Backend):
    FigureCanvas = FigureCanvasPdf
