import datetime
import numpy as np
from typing import Any, Callable, Iterable, Literal, Sequence
from matplotlib._typing import *
from matplotlib.figure import Figure
from matplotlib.backend_bases import _Backend

"""
This type stub file was generated by pyright.
"""

from .. import _api
from . import backend_agg, backend_gtk3
from .backend_gtk3 import _BackendGTK3

class FigureCanvasGTK3Agg(backend_gtk3.FigureCanvasGTK3, backend_agg.FigureCanvasAgg):
    def __init__(self, figure) -> None: ...
    def on_draw_event(self, widget, ctx): ...
    def blit(self, bbox=...): ...
    def draw(self): ...

class FigureManagerGTK3Agg(backend_gtk3.FigureManagerGTK3): ...

class _BackendGTK3Cairo(_BackendGTK3):
    FigureCanvas = FigureCanvasGTK3Agg
