from typing import Any

from .. import BaseProvider as BaseProvider
from .. import date_time as date_time

localized: bool

class Provider(BaseProvider):
    city_suffixes: Any = ...
    street_suffixes: Any = ...
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    building_number_formats: Any = ...
    postcode_formats: Any = ...
    countries: Any = ...
    ALPHA_2: str = ...
    ALPHA_3: str = ...
    alpha_2_country_codes: Any = ...
    alpha_3_country_codes: Any = ...
    def city_suffix(self): ...
    def street_suffix(self): ...
    def building_number(self): ...
    def city(self): ...
    def street_name(self): ...
    def street_address(self): ...
    def postcode(self): ...
    def address(self): ...
    def country(self): ...
    def country_code(self, representation: Any = ...): ...
