from typing import Any, Optional

class ISBN:
    MAX_LENGTH: int = ...
    ean: Any = ...
    group: Any = ...
    registrant: Any = ...
    publication: Any = ...
    def __init__(
        self,
        ean: Optional[Any] = ...,
        group: Optional[Any] = ...,
        registrant: Optional[Any] = ...,
        publication: Optional[Any] = ...,
    ) -> None: ...

class ISBN13(ISBN):
    check_digit: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def format(self, separator: str = ...): ...

class ISBN10(ISBN):
    check_digit: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def format(self, separator: str = ...): ...
