import pendulum
from ._extensions.helpers import days_in_year as days_in_year, is_leap as is_leap, is_long_year as is_long_year, local_time as local_time, precise_diff as precise_diff, timestamp as timestamp, week_day as week_day
from .constants import DAYS_PER_MONTHS as DAYS_PER_MONTHS
from .formatting.difference_formatter import DifferenceFormatter as DifferenceFormatter
from .locales.locale import Locale as Locale
from .period import Period as Period
from typing import Any, Iterator, Optional

with_extensions: Any
difference_formatter: Any

def add_duration(dt: _DT, years: int=..., months: int=..., weeks: int=..., days: int=..., hours: int=..., minutes: int=..., seconds: int=..., microseconds: int=...) -> _DT: ...
def format_diff(diff: Period, is_now: bool=..., absolute: bool=..., locale: Optional[str]=...) -> str: ...
def test(mock: pendulum.DateTime) -> Iterator[None]: ...
def set_test_now(test_now: Optional[pendulum.DateTime]=...) -> None: ...
def get_test_now() -> Optional[pendulum.DateTime]: ...
def has_test_now() -> bool: ...
def locale(name: str) -> Locale: ...
def set_locale(name: str) -> None: ...
def get_locale() -> str: ...
def week_starts_at(wday: int) -> None: ...
def week_ends_at(wday: int) -> None: ...
