from .constants import MONTHS_PER_YEAR as MONTHS_PER_YEAR
from .duration import Duration as Duration
from .helpers import precise_diff as precise_diff
from pendulum.utils._compat import decode as decode
from typing import Any, Optional

class Period(Duration):
    def __new__(cls, start: Any, end: Any, absolute: bool = ...): ...
    def __init__(self, start: Any, end: Any, absolute: bool = ...) -> None: ...
    @property
    def years(self): ...
    @property
    def months(self): ...
    @property
    def weeks(self): ...
    @property
    def days(self): ...
    @property
    def remaining_days(self): ...
    @property
    def hours(self): ...
    @property
    def minutes(self): ...
    @property
    def start(self): ...
    @property
    def end(self): ...
    def in_years(self): ...
    def in_months(self): ...
    def in_weeks(self): ...
    def in_days(self): ...
    def in_words(self, locale: Optional[Any] = ..., separator: str = ...): ...
    def range(self, unit: Any, amount: int = ...) -> None: ...
    def as_interval(self): ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: Any): ...
    def __add__(self, other: Any): ...
    __radd__: Any = ...
    def __sub__(self, other: Any): ...
    def __neg__(self): ...
    def __mul__(self, other: Any): ...
    __rmul__: Any = ...
    def __floordiv__(self, other: Any): ...
    def __truediv__(self, other: Any): ...
    __div__: Any = ...
    def __mod__(self, other: Any): ...
    def __divmod__(self, other: Any): ...
    def __abs__(self): ...
    def __reduce__(self): ...
    def __reduce_ex__(self, protocol: Any): ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
