from typing import Any

from .. import Provider as BaseProvider

class Provider(BaseProvider):
    nino_formats: Any = ...
    def ssn(self): ...
    vat_id_formats: Any = ...
    def vat_id(self): ...
