from .. import Provider as BaseProvider
from typing import Any

class Provider(BaseProvider):
    nino_formats: Any = ...
    def ssn(self): ...
    vat_id_formats: Any = ...
    def vat_id(self): ...
