def is_euler_pseudoprime(n, b) -> bool: ...
def is_square(n, prep=...) -> bool: ...
def mr(n, bases) -> bool: ...
def is_lucas_prp(n) -> bool: ...
def is_strong_lucas_prp(n) -> bool: ...
def is_extra_strong_lucas_prp(n) -> bool: ...
def is_mersenne_prime(n) -> bool: ...
def isprime(n) -> bool: ...
def is_gaussian_prime(num) -> bool: ...
