from typing import Any

from .. import Provider as SsnProvider

def checksum(digits: Any): ...

class Provider(SsnProvider):
    scale1: Any = ...
    scale2: Any = ...
    def ssn(self, min_age: int = ..., max_age: int = ...): ...
    vat_id_formats: Any = ...
    def vat_id(self): ...
