from typing import Any, Optional

from .. import Provider as AutomotiveProvider

class Provider(AutomotiveProvider):
    license_formats: Any = ...
    license_plate_new_format_suffix_letters: str = ...
    license_plate_old_format_suffix_letters: str = ...
    province_prefix: Any = ...
    def license_plate_unified(self): ...
    def license_plate_by_province(self, province_prefix: Optional[Any] = ...): ...
    def license_plate(self): ...
