from .. import Provider as PersonProvider
from typing import Any

def translit(text: Any): ...

class Provider(PersonProvider):
    formats_male: Any = ...
    formats_female: Any = ...
    formats: Any = ...
    first_names_male: Any = ...
    first_names_female: Any = ...
    first_names: Any = ...
    last_names_male: Any = ...
    last_names_female: Any = ...
    last_names: Any = ...
    middle_names_male: Any = ...
    middle_names_female: Any = ...
    middle_names: Any = ...
    language_names: Any = ...
    prefixes_male: Any = ...
    prefixes_female: Any = ...
    def middle_name(self): ...
    def middle_name_male(self): ...
    def middle_name_female(self): ...
