from pandas._typing import FilePathOrBuffer as FilePathOrBuffer, Scalar as Scalar
from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from pandas.io.excel._base import _BaseExcelReader
from typing import Any, List

class _PyxlsbReader(_BaseExcelReader):
    def __init__(self, filepath_or_buffer: FilePathOrBuffer) -> None: ...
    def load_workbook(self, filepath_or_buffer: FilePathOrBuffer) -> Any: ...
    @property
    def sheet_names(self) -> List[str]: ...
    def get_sheet_by_name(self, name: str) -> Any: ...
    def get_sheet_by_index(self, index: int) -> Any: ...
    def get_sheet_data(self, sheet: Any, convert_float: bool) -> List[List[Scalar]]: ...
