from typing import Any
from typing_extensions import TypeAlias

QT_API_PYQT6: str = ...
QT_API_PYSIDE6: str = ...
QT_API_PYQT5: str = ...
QT_API_PYSIDE2: str = ...
QT_API_ENV: str = ...

__version__: str
QtCore: TypeAlias = Any
QtWidgets: Any
