from typing import Any

from .. import Provider as PhoneNumberProvider

class Provider(PhoneNumberProvider):
    formats: Any = ...
    msisdn_formats: Any = ...
    cellphone_formats: Any = ...
    def cellphone_number(self): ...
