from .. import Provider as PhoneNumberProvider
from typing import Any

class Provider(PhoneNumberProvider):
    formats: Any = ...
    msisdn_formats: Any = ...
    cellphone_formats: Any = ...
    def cellphone_number(self): ...
