from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    address_formats: Any = ...
    building_number_formats: Any = ...
    city_formats: Any = ...
    street_address_formats: Any = ...
    street_name_formats: Any = ...
    city_prefixes: Any = ...
    countries: Any = ...
    street_prefixes: Any = ...
    street_suffixes: Any = ...
    street_titles: Any = ...
    def city_prefix(self): ...
    def postcode(self): ...
    def street_prefix(self): ...
    def street_title(self): ...
