from ... import exc as exc, pool as pool, util as util
from .base import DATE as DATE, DATETIME as DATETIME, SQLiteDialect as SQLiteDialect
from typing import Any

class _SQLite_pysqliteTimeStamp(DATETIME):
    def bind_processor(self, dialect: Any): ...
    def result_processor(self, dialect: Any, coltype: Any): ...

class _SQLite_pysqliteDate(DATE):
    def bind_processor(self, dialect: Any): ...
    def result_processor(self, dialect: Any, coltype: Any): ...

class SQLiteDialect_pysqlite(SQLiteDialect):
    default_paramstyle: str = ...
    colspecs: Any = ...
    description_encoding: Any = ...
    driver: str = ...
    @classmethod
    def dbapi(cls): ...
    @classmethod
    def get_pool_class(cls, url: Any): ...
    def set_isolation_level(self, connection: Any, level: Any): ...
    def create_connect_args(self, url: Any): ...
    def is_disconnect(self, e: Any, connection: Any, cursor: Any): ...
dialect = SQLiteDialect_pysqlite
