from .. import exc as exc, util as util
from ..dialects import plugins as plugins, registry as registry
from .interfaces import Dialect as Dialect
from typing import Any, Optional

class URL:
    drivername: Any = ...
    username: Any = ...
    password_original: Any = ...
    host: Any = ...
    port: Any = ...
    database: Any = ...
    query: Any = ...
    def __init__(self, drivername: Any, username: Optional[Any] = ..., password: Optional[Any] = ..., host: Optional[Any] = ..., port: Optional[Any] = ..., database: Optional[Any] = ..., query: Optional[Any] = ...) -> None: ...
    def __to_string__(self, hide_password: bool = ...): ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    @property
    def password(self): ...
    @password.setter
    def password(self, password: Any) -> None: ...
    def get_backend_name(self): ...
    def get_driver_name(self): ...
    def get_dialect(self): ...
    def translate_connect_args(self, names: Any = ..., **kw: Any): ...

def make_url(name_or_url: Any): ...
