from typing import Any

from .. import Provider as AutomotiveProvider

class Provider(AutomotiveProvider):
    license_plate_prefix: Any = ...
    license_plate_suffix: Any = ...
    def license_plate(self): ...
