from .. import Provider as AutomotiveProvider
from typing import Any

class Provider(AutomotiveProvider):
    license_plate_prefix: Any = ...
    license_plate_suffix: Any = ...
    def license_plate(self): ...
