from .. import Provider as BarcodeProvider
from typing import Any

class Provider(BarcodeProvider):
    local_prefixes: Any = ...
    def jan(self, length: int = ...): ...
    def jan8(self): ...
    def jan13(self): ...
