from typing import Callable, TypeVar

_CallableT = TypeVar("_CallableT", bound=Callable)

class _cache(list):
    def print_cache(self) -> None: ...
    def clear_cache(self) -> None: ...

CACHE = ...
print_cache = ...
clear_cache = ...
USE_CACHE = ...
scs = ...
SYMPY_CACHE_SIZE = ...

def cacheit(func: _CallableT) -> _CallableT: ...
def cached_property(func) -> property: ...
def lazy_function(module: str, name: str) -> Callable: ...
