rng = ...
choice = ...
random = ...
randint = ...
randrange = ...
sample = ...
shuffle = ...
uniform = ...
_assumptions_rng = ...
_assumptions_shuffle = ...

def seed(a=..., version=...) -> None: ...
def random_complex_number(a=..., b=..., c=..., d=..., rational=..., tolerance=...): ...
def verify_numerically(f, g, z=..., tol=..., a=..., b=..., c=..., d=...) -> bool: ...
def test_derivative_numerically(f, z, tol=..., a=..., b=..., c=..., d=...) -> bool: ...
