from pandas.core.base import PandasObject as PandasObject
#from pandas.io.formats.printing import pprint_thing as pprint_thing
from typing import Any

class FrozenList(PandasObject, list):
    def union(self, other: Any) -> FrozenList: ...
    def difference(self, other: Any) -> FrozenList: ...
    __add__: Any = ...
    __iadd__: Any = ...
    def __getitem__(self, n: Any): ...
    def __radd__(self, other: Any): ...
    def __eq__(self, other: Any) -> bool: ...
    __req__: Any = ...
    def __mul__(self, other: Any): ...
    __imul__: Any = ...
    def __reduce__(self): ...
    def __hash__(self) -> Any: ...
    __setitem__: Any = ...
    __setslice__: Any = ...
    __delitem__: Any = ...
    __delslice__: Any = ...
    pop: Any = ...
    append: Any = ...
    extend: Any = ...
    remove: Any = ...
    sort: Any = ...
    insert: Any = ...
