from ._shared import lazy as lazy
from ._shared.tester import PytestTester as PytestTester
from ._shared.version_requirements import ensure_python_version as ensure_python_version

__version__: str = ...
submodules: list = ...
__lazy_dir__ = ...

def __dir__(): ...

# Logic for checking for improper install and importing while in the source
# tree when package has not been installed inplace.
# Code adapted from scikit-learn's __check_build module.
_INPLACE_MSG: str = ...

_STANDARD_MSG: str = ...

def _raise_build_error(e): ...

test = ...
