from .timezone import Timezone as Timezone, TimezoneFile as TimezoneFile
from .zoneinfo.exceptions import InvalidTimezone as InvalidTimezone
from typing import Iterator, Optional, Union

def get_local_timezone() -> Timezone: ...
def set_local_timezone(mock: Optional[Union[str, Timezone]]=...) -> None: ...
def test_local_timezone(mock: Timezone) -> Iterator[None]: ...
