from typing import Union, Optional, Callable
from pandas.core.window.rolling import _Rolling

from pandas._typing import Scalar, Series, DataFrame

class ExponentialMovingWindow(_Rolling):
    obj = ...
    com = ...
    min_periods: int = ...
    adjust = ...
    ignore_na = ...
    axis = ...
    on = ...
    def __init__(
        self,
        obj,
        com=...,
        span=...,
        halflife=...,
        alpha=...,
        min_periods: int = ...,
        adjust: bool = ...,
        ignore_na: bool = ...,
        axis: int = ...,
    ) -> None: ...
    def aggregate(self, func: Optional[Callable] = ..., *args, **kwargs) -> Union[Scalar, Series, DataFrame]: ...
    agg = aggregate
    def mean(self, *args, **kwargs): ...
    def std(self, bias: bool = ..., *args, **kwargs): ...
    vol = ...
    def var(self, bias: bool = ..., *args, **kwargs): ...
    def cov(self, other=..., pairwise=..., bias: bool = ..., **kwargs): ...
    def corr(self, other=..., pairwise=..., **kwargs): ...
