from .. import Provider as PersonProvider
from typing import Any

class Provider(PersonProvider):
    formats: Any = ...
    first_names_male: Any = ...
    first_names_female: Any = ...
    first_names: Any = ...
    last_names: Any = ...
    romanized_formats: Any = ...
    first_romanized_names: Any = ...
    last_romanized_names: Any = ...
    def romanized_name(self): ...
    def first_romanized_name(self): ...
    def last_romanized_name(self): ...
