from typing import Any

from .. import Provider as SsnProvider

class Provider(SsnProvider):
    def ssn(self, min_age: int = ..., max_age: int = ..., artificial: bool = ...): ...
    vat_id_formats: Any = ...
    def vat_id(self): ...
