from typing import Any

from ..en import Provider as AddressProvider

class Provider(AddressProvider):
    city_prefixes: Any = ...
    city_suffixes: Any = ...
    counties: Any = ...
    building_number_formats: Any = ...
    street_suffixes: Any = ...
    POSTAL_ZONES: Any = ...
    POSTAL_ZONES_ONE_CHAR: Any = ...
    POSTAL_ZONES_TWO_CHARS: Any = ...
    postcode_formats: Any = ...
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    secondary_address_formats: Any = ...
    def postcode(self): ...
    def city_prefix(self): ...
    def secondary_address(self): ...
    def county(self): ...
