from enum import Enum

class Feature(Enum):
    ALL = "ALL"
    AUTO_CONTROL_DEPS = "AUTO_CONTROL_DEPS"
    ASSERT_STATEMENTS = "ASSERT_STATEMENTS"
    BUILTIN_FUNCTIONS = "BUILTIN_FUNCTIONS"
    EQUALITY_OPERATORS = "EQUALITY_OPERATORS"
    LISTS = "LISTS"
    NAME_SCOPES = "NAME_SCOPES"
