
# This file is generated by docs2stub. These types are intended
# to simplify the stubs generated by docs2stub. They are not
# intended to be used directly by other users.

import decimal
import io
import numpy.typing
import numpy as np
import pandas as pd
from .base import BaseEstimator, ClassifierMixin, RegressorMixin
from scipy.sparse import spmatrix
from typing_extensions import TypeAlias


Decimal: TypeAlias = decimal.Decimal
PythonScalar: TypeAlias = str | int | float | bool

ArrayLike: TypeAlias = numpy.typing.ArrayLike
MatrixLike: TypeAlias = np.ndarray | pd.DataFrame | spmatrix
FileLike: TypeAlias = io.IOBase
PathLike: TypeAlias = str
Int: TypeAlias = int | np.int8 | np.int16 | np.int32 | np.int64
Float: TypeAlias = float | np.float16 | np.float32 | np.float64

PandasScalar: TypeAlias = pd.Period | pd.Timestamp | pd.Timedelta | pd.Interval
Scalar: TypeAlias = PythonScalar | PandasScalar

Estimator: TypeAlias = BaseEstimator
Classifier: TypeAlias = ClassifierMixin
Regressor: TypeAlias = RegressorMixin

Color = tuple[float, float, float] | str

        