from numpy.typing import ArrayLike
from os import environ
from functools import wraps
import platform
import sys

import pytest
import numpy as np
from threadpoolctl import threadpool_limits
from _pytest.doctest import DoctestItem

from sklearn.utils import _IS_32BIT
from sklearn.utils._openmp_helpers import _openmp_effective_n_threads
from sklearn._min_dependencies import PYTEST_MIN_VERSION
from sklearn.utils.fixes import parse_version
from sklearn.datasets import fetch_20newsgroups
from sklearn.datasets import fetch_20newsgroups_vectorized
from sklearn.datasets import fetch_california_housing
from sklearn.datasets import fetch_covtype
from sklearn.datasets import fetch_kddcup99
from sklearn.datasets import fetch_olivetti_faces
from sklearn.datasets import fetch_rcv1
from sklearn.tests import random_seed

dataset_fetchers: dict = ...

_SKIP32_MARK = ...

# Global fixtures
@pytest.fixture(params=[pytest.param(np.float32, marks=_SKIP32_MARK), np.float64])
def global_dtype(request): ...
def _fetch_fixture(f): ...

# Adds fixtures for fetching data
fetch_20newsgroups_fxt = ...
fetch_20newsgroups_vectorized_fxt = ...
fetch_california_housing_fxt = ...
fetch_covtype_fxt = ...
fetch_kddcup99_fxt = ...
fetch_olivetti_faces_fxt = ...
fetch_rcv1_fxt = ...

def pytest_collection_modifyitems(config, items: list): ...
@pytest.fixture(scope="function")
def pyplot() -> module: ...
def pytest_runtest_setup(item): ...
def pytest_configure(config): ...
