from .. import Provider as AddressProvider
from typing import Any

class Provider(AddressProvider):
    city_suffixes: Any = ...
    street_prefixes: Any = ...
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    building_number_formats: Any = ...
    postcode_raw_formats: Any = ...
    postcode_all_formats: Any = ...
    bairros: Any = ...
    countries: Any = ...
    estados: Any = ...
    def street_prefix(self): ...
    def estado(self): ...
    def estado_nome(self): ...
    def estado_sigla(self): ...
    def bairro(self): ...
    def postcode(self, formatted: bool = ...): ...
    def neighborhood(self): ...
    def state(self): ...
    def state_abbr(self): ...
