from .. import Provider as CompanyProvider
from typing import Any

class Provider(CompanyProvider):
    formats: Any = ...
    company_suffixes: Any = ...
    def company_business_id(self): ...
    def company_vat(self): ...
