from typing import Any

PY37: Any
PY38: Any
PYPY: Any

def set_function_name(f: Any, name: Any, cls: Any): ...
def is_platform_little_endian() -> bool: ...
def is_platform_windows() -> bool: ...
def is_platform_linux() -> bool: ...
def is_platform_mac() -> bool: ...
def is_platform_32bit() -> bool: ...
