import pickle as pkl
from pandas import DataFrame as DataFrame, Index as Index, Series as Series
from typing import Optional

def load_reduce(self) -> None: ...

class _LoadSparseSeries:
    def __new__(cls) -> Series: ...

class _LoadSparseFrame:
    def __new__(cls) -> DataFrame: ...

class Unpickler(pkl._Unpickler):
    def find_class(self, module, name: str): ...

def load_newobj(self) -> None: ...
def load_newobj_ex(self) -> None: ...
def load(fh, encoding: Optional[str]=..., is_verbose: bool=...): ...
