from typing import Tuple
from pygame.mixer import Sound
from numpy import ndarray

def array(sound: Sound) -> ndarray: ...
def samples(sound: Sound) -> ndarray: ...
def make_sound(array: ndarray) -> Sound: ...
def use_arraytype(arraytype: str) -> Sound: ...
def get_arraytype() -> str: ...
def get_arraytypes() -> Tuple[str]: ...

