import numpy as np
from typing import Literal
from ._typing import *
import contextlib
from packaging.version import parse as parse_version
from . import _docstring, _version, cbook, rcsetup

class __getattr__:

    URL_REGEX = ...

def set_loglevel(
    level: Literal["notset", "debug", "info", "warning", "error", "critical"]
): ...

class ExecutableNotFoundError(FileNotFoundError): ...

def checkdep_usetex(s): ...
def get_configdir() -> str: ...
def get_cachedir() -> str: ...
def get_data_path() -> str: ...
def matplotlib_fname() -> str: ...

class RcParams(dict):

    validate = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def find_all(self, pattern): ...
    def copy(self): ...

def rc_params(fail_on_error: bool = ...) -> RcParams: ...
def is_url(filename: str) -> bool: ...
def rc_params_from_file(
    fname: str | PathLike, fail_on_error: bool = ..., use_default_template: bool = ...
) -> RcParams: ...

rcParamsDefault: RcParams = ...
rcParams: RcParams = ...
rcParamsOrig: RcParams = ...

def rc(group, **kwargs): ...
def rcdefaults(): ...
def rc_file_defaults(): ...
def rc_file(fname: str | PathLike, *, use_default_template: bool = ...): ...
@contextlib.contextmanager
def rc_context(rc: dict = ..., fname: str | PathLike = ...): ...
def use(backend: str, *, force: bool = True): ...
def get_backend() -> str: ...
def interactive(b) -> bool: ...
def is_interactive() -> bool: ...

default_test_modules = ...

def test(verbosity=..., coverage=..., **kwargs): ...
