
NO_GLOBAL = ...
def init_printing(pretty_print=..., order=..., use_unicode=..., use_latex=..., wrap_line=..., num_columns=..., no_global=..., ip=..., euler=..., forecolor=..., backcolor=..., fontsize=..., latex_mode=..., print_builtin=..., str_printer=..., pretty_printer=..., latex_printer=..., scale=..., **settings) -> None:
    ...

