from code import InteractiveConsole
from typing import Any

preexec_source = ...
verbose_message = ...
no_ipython = ...
def int_to_Integer(s) -> Any:
    ...

def enable_automatic_int_sympification(shell) -> None:
    ...

def enable_automatic_symbols(shell) -> None:
    ...

def init_ipython_session(shell=..., argv=..., auto_symbols=..., auto_int_to_Integer=...) -> Any:
    ...

def init_python_session() -> InteractiveConsole:
    class SymPyConsole(InteractiveConsole):
        ...
    
    

def init_session(ipython=..., pretty_print=..., order=..., use_unicode=..., use_latex=..., quiet=..., auto_symbols=..., auto_int_to_Integer=..., str_printer=..., pretty_printer=..., latex_printer=..., argv=...) -> None:
    ...

