from sympy.printing.pretty.stringpict import prettyForm
from sympy.printing.printer import Printer, print_function

pprint_use_unicode = ...
pprint_try_use_unicode = ...
class PrettyPrinter(Printer):
    printmethod = ...
    _default_settings = ...
    def __init__(self, settings=...) -> None:
        ...
    
    def emptyPrinter(self, expr) -> prettyForm:
        ...
    
    def doprint(self, expr):
        ...
    
    _print_RandomSymbol = ...
    _print_Infinity = ...
    _print_NegativeInfinity = ...
    _print_EmptySet = ...
    _print_Naturals = ...
    _print_Naturals0 = ...
    _print_Integers = ...
    _print_Rationals = ...
    _print_Complexes = ...
    _print_EmptySequence = ...
    _print_SeqPer = ...
    _print_SeqAdd = ...
    _print_SeqMul = ...
    def join(self, delimiter, args) -> prettyForm:
        ...
    
    _print_bell = ...


@print_function(PrettyPrinter)
def pretty(expr, **settings):
    ...

def pretty_print(expr, **kwargs) -> None:
    ...

pprint = ...
def pager_print(expr, **settings) -> None:
    ...

