unicode_warnings = ...

def U(name) -> str | None: ...

__all__ = ["greek_unicode", "sub", "sup", "xsym", "vobj", "hobj", "pretty_symbol", "annotated"]
_use_unicode = ...

def pretty_use_unicode(flag=...) -> bool: ...
def pretty_try_use_unicode() -> None: ...
def xstr(*args) -> str: ...

g = ...
G = ...
greek_letters = ...
greek_unicode = ...
b = ...
B = ...
bold_unicode = ...
gb = ...
GB = ...
greek_bold_letters = ...
greek_bold_unicode = ...
digit_2txt = ...
symb_2txt = ...
LSUB = ...
GSUB = ...
DSUB = ...
SSUB = ...
LSUP = ...
DSUP = ...
SSUP = ...
sub = ...
sup = ...
modifier_dict = ...
HUP = ...
CUP = ...
MID = ...
EXT = ...
HLO = ...
CLO = ...
TOP = ...
BOT = ...
_xobj_unicode = ...
_xobj_ascii = ...

def xobj(symb, length): ...
def vobj(symb, height) -> str: ...
def hobj(symb, width) -> str: ...

root = ...
VF = ...
frac = ...
_xsym = ...

def xsym(sym): ...

atoms_table = ...

def pretty_atom(atom_name, default=..., printer=...) -> str | None: ...
def pretty_symbol(symb_name, bold_name=...) -> str: ...
def annotated(letter): ...

_remove_combining = ...

def is_combining(sym) -> bool: ...
def center_accent(string, accent): ...
def line_width(line) -> int: ...
