from .. import Provider as PersonProvider
from typing import Any

class Provider(PersonProvider):
    formats_male: Any = ...
    formats_female: Any = ...
    formats: Any = ...
    last_names: Any = ...
    first_names_male: Any = ...
    first_names_female: Any = ...
    first_names: Any = ...
    prefixes: Any = ...
    def first_name_male_abbreviated(self): ...
    def first_name_female_abbreviated(self): ...
