from .base import BaseApplicationBackend

ApplicationBackend = BaseApplicationBackend

class Application:
    def __init__(self, backend_name: str | None = None): ...
    def __repr__(self): ...
    @property
    def backend_name(self): ...
    @property
    def backend_module(self): ...
    def process_events(self): ...
    def sleep(self, duration_sec: float): ...
    def create(self): ...
    def is_interactive(self): ...
    def is_notebook(self): ...
    def run(self, allow_interactive: bool = True): ...
    def reuse(self): ...
    def quit(self): ...
    @property
    def native(self): ...
    def _use(self, backend_name=None): ...
