from collections.abc import Generator
from typing import Any, Literal

def minisat22_satisfiable(
    expr, all_models=..., minimal=...
) -> Generator[bool] | Generator[dict[Any, Any] | Literal[False]] | dict[Any, Any] | Literal[False]: ...
