from collections.abc import Generator
from typing import Any, Literal

def pycosat_satisfiable(
    expr, all_models=...
) -> Generator[bool] | dict[Any, Any] | Generator[dict[Any, Any] | Literal[False]] | Literal[False]: ...
