from typing import Any, Optional

from faker.providers.person.ru_RU import translit as translit

from .. import CreditCard as CreditCard
from .. import Provider as CreditCardProvider

class Provider(CreditCardProvider):
    prefix_visa: Any = ...
    prefix_mastercard: Any = ...
    prefix_mir: Any = ...
    prefix_maestro: Any = ...
    prefix_amex: Any = ...
    prefix_unionpay: Any = ...
    credit_card_types: Any = ...
    def credit_card_expire(
        self, start: str = ..., end: str = ..., date_format: str = ...
    ): ...
    def credit_card_full(self, card_type: Optional[Any] = ...): ...
