__all__ = [
    "no_filter",
    "hide_nodes",
    "hide_edges",
    "hide_multiedges",
    "hide_diedges",
    "hide_multidiedges",
    "show_nodes",
    "show_edges",
    "show_multiedges",
    "show_diedges",
    "show_multidiedges",
]

def no_filter(*items): ...
def hide_nodes(nodes): ...
def hide_diedges(edges): ...
def hide_edges(edges): ...
def hide_multidiedges(edges): ...
def hide_multiedges(edges): ...

# write show_nodes as a class to make SubGraph pickleable
class show_nodes:
    def __init__(self, nodes): ...
    def __call__(self, node): ...

def show_diedges(edges): ...
def show_edges(edges): ...
def show_multidiedges(edges): ...
def show_multiedges(edges): ...
