from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    city_formats: Any = ...
    building_number_formats: Any = ...
    postcode_formats: Any = ...
    section_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    secondary_address_formats: Any = ...
    street_names: Any = ...
    street_suffixes: Any = ...
    cities: Any = ...
    city_suffixes: Any = ...
    countries: Any = ...
    def secondary_address(self): ...
    def building_number(self): ...
    def street_name(self): ...
    def street_name_suffix(self): ...
    def city_name(self): ...
    def city_name_suffix(self): ...
    def section_number(self): ...
