from typing import Any, Optional

from .. import BaseProvider as BaseProvider

localized: bool

class CreditCard:
    name: Any = ...
    prefixes: Any = ...
    length: Any = ...
    security_code: Any = ...
    security_code_length: Any = ...
    def __init__(
        self,
        name: Any,
        prefixes: Any,
        length: int = ...,
        security_code: str = ...,
        security_code_length: int = ...,
    ) -> None: ...

class Provider(BaseProvider):
    prefix_maestro: Any = ...
    prefix_mastercard: Any = ...
    prefix_visa: Any = ...
    prefix_amex: Any = ...
    prefix_discover: Any = ...
    prefix_diners: Any = ...
    prefix_jcb16: Any = ...
    prefix_jcb15: Any = ...
    credit_card_types: Any = ...
    luhn_lookup: Any = ...
    def credit_card_provider(self, card_type: Optional[Any] = ...): ...
    def credit_card_number(self, card_type: Optional[Any] = ...): ...
    def credit_card_expire(
        self, start: str = ..., end: str = ..., date_format: str = ...
    ): ...
    def credit_card_full(self, card_type: Optional[Any] = ...): ...
    def credit_card_security_code(self, card_type: Optional[Any] = ...): ...
