from .. import Provider as PersonProvider
from typing import Any

class Provider(PersonProvider):
    formats: Any = ...
    prefixes_female: Any = ...
    prefixes_male: Any = ...
    prefixes: Any = ...
    first_names: Any = ...
    last_names: Any = ...
    suffixes: Any = ...
