from . import Extension as Extension
from ..blockprocessors import OListProcessor as OListProcessor, UListProcessor as UListProcessor
from typing import Any

class SaneOListProcessor(OListProcessor):
    SIBLING_TAGS: Any = ...
    LAZY_OL: bool = ...
    CHILD_RE: Any = ...
    def __init__(self, parser: Any) -> None: ...

class SaneUListProcessor(UListProcessor):
    SIBLING_TAGS: Any = ...
    CHILD_RE: Any = ...
    def __init__(self, parser: Any) -> None: ...

class SaneListExtension(Extension):
    def extendMarkdown(self, md: Any) -> None: ...

def makeExtension(**kwargs: Any): ...
