from .. import Provider as SsnProvider
from typing import Any

def checksum(digits: Any): ...
def calculate_month(birth_date: Any): ...

class Provider(SsnProvider):
    def ssn(self): ...
    vat_id_formats: Any = ...
    def vat_id(self): ...
