from .. import Provider as InternetProvider
from typing import Any

class Provider(InternetProvider):
    user_name_formats: Any = ...
    email_formats: Any = ...
    free_email_domains: Any = ...
    tlds: Any = ...
