from typing import Any

def int_to_boolean(*args, **kwargs) -> Any: ...
def str_to_date(*args, **kwargs) -> Any: ...
def str_to_datetime(*args, **kwargs) -> Any: ...
def str_to_time(*args, **kwargs) -> Any: ...
def to_float(*args, **kwargs) -> Any: ...
def to_str(*args, **kwargs) -> Any: ...

class DecimalResultProcessor:
    def __init__(self, *args, **kwargs) -> None: ...
    def process(self, *args, **kwargs) -> Any: ...

class UnicodeResultProcessor:
    def __init__(self, *args, **kwargs) -> None: ...
    def conditional_process(self, *args, **kwargs) -> Any: ...
    def process(self, *args, **kwargs) -> Any: ...
