from typing import Any, Optional

from .. import BaseProvider as BaseProvider
from .color import RandomColor as RandomColor

localized: bool

class Provider(BaseProvider):
    all_colors: Any = ...
    safe_colors: Any = ...
    def color_name(self): ...
    def safe_color_name(self): ...
    def hex_color(self): ...
    def safe_hex_color(self): ...
    def rgb_color(self): ...
    def rgb_css_color(self): ...
    def color(
        self,
        hue: Optional[Any] = ...,
        luminosity: Optional[Any] = ...,
        color_format: str = ...,
    ): ...
