from typing import Any, Optional

COLOR_MAP: Any

class RandomColor:
    colormap: Any = ...
    random: Any = ...
    seed: Any = ...
    def __init__(
        self, generator: Optional[Any] = ..., seed: Optional[Any] = ...
    ) -> None: ...
    def generate(
        self,
        hue: Optional[Any] = ...,
        luminosity: Optional[Any] = ...,
        color_format: str = ...,
    ): ...
    def pick_hue(self, hue: Any): ...
    def pick_saturation(self, hue: Any, hue_name: Any, luminosity: Any): ...
    def pick_brightness(self, h: Any, s: Any, luminosity: Any): ...
    def set_format(self, hsv: Any, color_format: Any): ...
    def get_minimum_brightness(self, h: Any, s: Any): ...
    def get_hue_range(self, color_input: Any): ...
    def get_saturation_range(self, hue: Any): ...
    def get_color_info(self, hue: Any): ...
    def random_within(self, r: Any): ...
    @classmethod
    def hsv_to_rgb(cls, hsv: Any): ...
    @classmethod
    def hsv_to_hsl(cls, hsv: Any): ...
