from collections.abc import Generator
from typing import Any

from sympy.combinatorics.permutations import Permutation

def symmetric(n) -> Generator[Permutation]: ...
def cyclic(n) -> Generator[Permutation]: ...
def alternating(n) -> Generator[Permutation]: ...
def dihedral(n) -> Generator[Permutation]: ...
def rubik_cube_generators() -> list[Permutation]: ...
def rubik(n) -> list[Any]: ...
