# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: win32api, version: unspecified
# Module: win32api, version: unspecified

'Wraps general API functions that are not subsumed in the more specific modules'

import typing
import builtins as _mod_builtins
from .lib import pywintypes as _mod_pywintypes

def AbortSystemShutdown() -> typing.Any:
    ...

def Apply() -> typing.Any:
    ...

def Beep() -> typing.Any:
    ...

def BeginUpdateResource() -> typing.Any:
    ...

def ChangeDisplaySettings() -> typing.Any:
    ...

def ChangeDisplaySettingsEx() -> typing.Any:
    ...

def ClipCursor() -> typing.Any:
    ...

def CloseHandle() -> typing.Any:
    ...

def CommandLineToArgv() -> typing.Any:
    ...

def CopyFile() -> typing.Any:
    ...

def DebugBreak() -> typing.Any:
    ...

def DeleteFile() -> typing.Any:
    ...

def DragFinish() -> typing.Any:
    ...

def DragQueryFile() -> typing.Any:
    ...

def DuplicateHandle() -> typing.Any:
    ...

def EndUpdateResource() -> typing.Any:
    ...

def EnumDisplayDevices() -> typing.Any:
    ...

def EnumDisplayMonitors() -> typing.Any:
    ...

def EnumDisplaySettings() -> typing.Any:
    ...

def EnumDisplaySettingsEx() -> typing.Any:
    ...

def EnumResourceLanguages() -> typing.Any:
    ...

def EnumResourceNames() -> typing.Any:
    ...

def EnumResourceTypes() -> typing.Any:
    ...

def ExitWindows() -> typing.Any:
    ...

def ExitWindowsEx() -> typing.Any:
    ...

def ExpandEnvironmentStrings() -> typing.Any:
    ...

def FindCloseChangeNotification() -> typing.Any:
    ...

def FindExecutable() -> typing.Any:
    ...

def FindFiles() -> typing.Any:
    ...

def FindFirstChangeNotification() -> typing.Any:
    ...

def FindNextChangeNotification() -> typing.Any:
    ...

def FormatMessage() -> typing.Any:
    ...

def FormatMessageW() -> typing.Any:
    ...

def FreeLibrary() -> typing.Any:
    ...

def GenerateConsoleCtrlEvent() -> typing.Any:
    ...

def GetAsyncKeyState() -> typing.Any:
    ...

def GetCommandLine() -> typing.Any:
    ...

def GetComputerName() -> typing.Any:
    ...

def GetComputerNameEx() -> typing.Any:
    ...

def GetComputerObjectName() -> typing.Any:
    ...

def GetConsoleTitle() -> typing.Any:
    ...

def GetCurrentProcess() -> typing.Any:
    ...

def GetCurrentProcessId() -> typing.Any:
    ...

def GetCurrentThread() -> typing.Any:
    ...

def GetCurrentThreadId() -> typing.Any:
    ...

def GetCursorPos() -> typing.Any:
    ...

def GetDateFormat() -> typing.Any:
    ...

def GetDiskFreeSpace() -> typing.Any:
    ...

def GetDiskFreeSpaceEx() -> typing.Any:
    ...

def GetDllDirectory() -> typing.Any:
    ...

def GetDomainName() -> typing.Any:
    ...

def GetEnvironmentVariable() -> typing.Any:
    ...

def GetEnvironmentVariableW() -> typing.Any:
    ...

def GetFileAttributes() -> typing.Any:
    ...

def GetFileVersionInfo() -> typing.Any:
    ...

def GetFocus() -> typing.Any:
    ...

def GetFullPathName() -> typing.Any:
    ...

def GetHandleInformation() -> typing.Any:
    ...

def GetKeyState() -> typing.Any:
    ...

def GetKeyboardLayout() -> typing.Any:
    ...

def GetKeyboardLayoutList() -> typing.Any:
    ...

def GetKeyboardLayoutName() -> typing.Any:
    ...

def GetKeyboardState() -> typing.Any:
    ...

def GetLastError() -> typing.Any:
    ...

def GetLastInputInfo() -> typing.Any:
    ...

def GetLocalTime() -> typing.Any:
    ...

def GetLogicalDriveStrings() -> typing.Any:
    ...

def GetLogicalDrives() -> typing.Any:
    ...

def GetLongPathName() -> typing.Any:
    ...

def GetLongPathNameW() -> typing.Any:
    ...

def GetModuleFileName() -> typing.Any:
    ...

def GetModuleFileNameW() -> typing.Any:
    ...

def GetModuleHandle() -> typing.Any:
    ...

def GetMonitorInfo() -> typing.Any:
    ...

def GetNativeSystemInfo() -> typing.Any:
    ...

def GetProcAddress() -> typing.Any:
    ...

def GetProfileSection() -> typing.Any:
    ...

def GetProfileVal() -> typing.Any:
    ...

def GetPwrCapabilities() -> typing.Any:
    ...

def GetShortPathName() -> typing.Any:
    ...

def GetStdHandle() -> typing.Any:
    ...

def GetSysColor() -> typing.Any:
    ...

def GetSystemDefaultLCID() -> typing.Any:
    ...

def GetSystemDefaultLangID() -> typing.Any:
    ...

def GetSystemDirectory() -> typing.Any:
    ...

def GetSystemFileCacheSize() -> typing.Any:
    ...

def GetSystemInfo() -> typing.Any:
    ...

def GetSystemMetrics() -> typing.Any:
    ...

def GetSystemTime() -> typing.Any:
    ...

def GetTempFileName() -> typing.Any:
    ...

def GetTempPath() -> typing.Any:
    ...

def GetThreadLocale() -> typing.Any:
    ...

def GetTickCount() -> typing.Any:
    ...

def GetTimeFormat() -> typing.Any:
    ...

def GetTimeZoneInformation() -> typing.Any:
    ...

def GetUserDefaultLCID() -> typing.Any:
    ...

def GetUserDefaultLangID() -> typing.Any:
    ...

def GetUserName() -> typing.Any:
    ...

def GetUserNameEx() -> typing.Any:
    ...

def GetVersion() -> typing.Any:
    ...

def GetVersionEx() -> typing.Any:
    ...

def GetVolumeInformation() -> typing.Any:
    ...

def GetWindowLong() -> typing.Any:
    ...

def GetWindowsDirectory() -> typing.Any:
    ...

def GlobalMemoryStatus() -> typing.Any:
    ...

def GlobalMemoryStatusEx() -> typing.Any:
    ...

def HIBYTE() -> typing.Any:
    ...

def HIWORD() -> typing.Any:
    ...

def InitiateSystemShutdown() -> typing.Any:
    ...

def LOBYTE() -> typing.Any:
    ...

def LOWORD() -> typing.Any:
    ...

def LoadCursor() -> typing.Any:
    ...

def LoadKeyboardLayout() -> typing.Any:
    ...

def LoadLibrary() -> typing.Any:
    ...

def LoadLibraryEx() -> typing.Any:
    ...

def LoadResource() -> typing.Any:
    ...

def LoadString() -> typing.Any:
    ...

def MAKELANGID() -> typing.Any:
    ...

def MAKELONG() -> typing.Any:
    ...

def MAKEWORD() -> typing.Any:
    ...

def MapVirtualKey() -> typing.Any:
    ...

def MessageBeep() -> typing.Any:
    ...

def MessageBox() -> typing.Any:
    ...

def MessageBoxEx() -> typing.Any:
    ...

def MonitorFromPoint() -> typing.Any:
    ...

def MonitorFromRect() -> typing.Any:
    ...

def MonitorFromWindow() -> typing.Any:
    ...

def MoveFile() -> typing.Any:
    ...

def MoveFileEx() -> typing.Any:
    ...

NameCanonical: int
NameCanonicalEx: int
NameDisplay: int
NameFullyQualifiedDN: int
NameSamCompatible: int
NameServicePrincipal: int
NameUniqueId: int
NameUnknown: int
NameUserPrincipal: int
def OpenProcess() -> typing.Any:
    ...

def OpenThread() -> typing.Any:
    ...

def OutputDebugString() -> typing.Any:
    ...

def PostMessage() -> typing.Any:
    ...

def PostQuitMessage() -> typing.Any:
    ...

def PostThreadMessage() -> typing.Any:
    ...

PyDISPLAY_DEVICEType = _mod_builtins.PyDISPLAY_DEVICE
REG_NOTIFY_CHANGE_ATTRIBUTES: int
REG_NOTIFY_CHANGE_LAST_SET: int
REG_NOTIFY_CHANGE_NAME: int
REG_NOTIFY_CHANGE_SECURITY: int
def RGB() -> typing.Any:
    ...

def RegCloseKey() -> typing.Any:
    ...

def RegConnectRegistry() -> typing.Any:
    ...

def RegCopyTree() -> typing.Any:
    ...

def RegCreateKey() -> typing.Any:
    ...

def RegCreateKeyEx() -> typing.Any:
    ...

def RegDeleteKey() -> typing.Any:
    ...

def RegDeleteKeyEx() -> typing.Any:
    ...

def RegDeleteTree() -> typing.Any:
    ...

def RegDeleteValue() -> typing.Any:
    ...

def RegEnumKey() -> typing.Any:
    ...

def RegEnumKeyEx() -> typing.Any:
    ...

def RegEnumKeyExW() -> typing.Any:
    ...

def RegEnumValue() -> typing.Any:
    ...

def RegFlushKey() -> typing.Any:
    ...

def RegGetKeySecurity() -> typing.Any:
    ...

def RegLoadKey() -> typing.Any:
    ...

def RegNotifyChangeKeyValue() -> typing.Any:
    ...

def RegOpenCurrentUser() -> typing.Any:
    ...

def RegOpenKey() -> typing.Any:
    ...

def RegOpenKeyEx() -> typing.Any:
    ...

def RegOpenKeyTransacted() -> typing.Any:
    ...

def RegOverridePredefKey() -> typing.Any:
    ...

def RegQueryInfoKey() -> typing.Any:
    ...

def RegQueryInfoKeyW() -> typing.Any:
    ...

def RegQueryValue() -> typing.Any:
    ...

def RegQueryValueEx() -> typing.Any:
    ...

def RegRestoreKey() -> typing.Any:
    ...

def RegSaveKey() -> typing.Any:
    ...

def RegSaveKeyEx() -> typing.Any:
    ...

def RegSetKeySecurity() -> typing.Any:
    ...

def RegSetValue() -> typing.Any:
    ...

def RegSetValueEx() -> typing.Any:
    ...

def RegUnLoadKey() -> typing.Any:
    ...

def RegisterWindowMessage() -> typing.Any:
    ...

STD_ERROR_HANDLE: int
STD_INPUT_HANDLE: int
STD_OUTPUT_HANDLE: int
def SearchPath() -> typing.Any:
    ...

def SendMessage() -> typing.Any:
    ...

def SetClassLong() -> typing.Any:
    ...

def SetClassWord() -> typing.Any:
    ...

def SetConsoleCtrlHandler() -> typing.Any:
    ...

def SetConsoleTitle() -> typing.Any:
    ...

def SetCursor() -> typing.Any:
    ...

def SetCursorPos() -> typing.Any:
    ...

def SetDllDirectory() -> typing.Any:
    ...

def SetEnvironmentVariable() -> typing.Any:
    ...

def SetEnvironmentVariableW() -> typing.Any:
    ...

def SetErrorMode() -> typing.Any:
    ...

def SetFileAttributes() -> typing.Any:
    ...

def SetHandleInformation() -> typing.Any:
    ...

def SetLastError() -> typing.Any:
    ...

def SetLocalTime() -> typing.Any:
    ...

def SetStdHandle() -> typing.Any:
    ...

def SetSysColors() -> typing.Any:
    ...

def SetSystemFileCacheSize() -> typing.Any:
    ...

def SetSystemPowerState() -> typing.Any:
    ...

def SetSystemTime() -> typing.Any:
    ...

def SetThreadLocale() -> typing.Any:
    ...

def SetTimeZoneInformation() -> typing.Any:
    ...

def SetWindowLong() -> typing.Any:
    ...

def ShellExecute() -> typing.Any:
    ...

def ShowCursor() -> typing.Any:
    ...

def Sleep() -> typing.Any:
    ...

def SleepEx() -> typing.Any:
    ...

def TerminateProcess() -> typing.Any:
    ...

def ToAsciiEx() -> typing.Any:
    ...

def Unicode() -> typing.Any:
    ...

def UpdateResource() -> typing.Any:
    ...

VFT_APP: int
VFT_DLL: int
VFT_DRV: int
VFT_FONT: int
VFT_STATIC_LIB: int
VFT_UNKNOWN: int
VFT_VXD: int
VOS_DOS: int
VOS_DOS_WINDOWS16: int
VOS_DOS_WINDOWS32: int
VOS_NT: int
VOS_NT_WINDOWS32: int
VOS_OS216: int
VOS_OS216_PM16: int
VOS_OS232: int
VOS_OS232_PM32: int
VOS_UNKNOWN: int
VOS__PM16: int
VOS__PM32: int
VOS__WINDOWS16: int
VOS__WINDOWS32: int
VS_FF_DEBUG: int
VS_FF_INFOINFERRED: int
VS_FF_PATCHED: int
VS_FF_PRERELEASE: int
VS_FF_PRIVATEBUILD: int
VS_FF_SPECIALBUILD: int
def VkKeyScan() -> typing.Any:
    ...

def VkKeyScanEx() -> typing.Any:
    ...

def WinExec() -> typing.Any:
    ...

def WinHelp() -> typing.Any:
    ...

def WriteProfileSection() -> typing.Any:
    ...

def WriteProfileVal() -> typing.Any:
    ...

__doc__: str
__file__: str
__name__: str
__package__: str
error = _mod_pywintypes.error
def keybd_event() -> typing.Any:
    ...

def mouse_event() -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

