# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: win32crypt, version: unspecified
# Module: win32crypt, version: unspecified

'Support for Windows cryptography functions'

import typing
import builtins as _mod_builtins

def CertAddSerializedElementToStore() -> typing.Any:
    ...

def CertAlgIdToOID() -> typing.Any:
    ...

def CertEnumPhysicalStore() -> typing.Any:
    ...

def CertEnumSystemStore() -> typing.Any:
    ...

def CertEnumSystemStoreLocation() -> typing.Any:
    ...

def CertNameToStr() -> typing.Any:
    ...

def CertOIDToAlgId() -> typing.Any:
    ...

def CertOpenStore() -> typing.Any:
    ...

def CertOpenSystemStore() -> typing.Any:
    ...

def CertRegisterSystemStore() -> typing.Any:
    ...

def CertUnregisterSystemStore() -> typing.Any:
    ...

def CryptAcquireContext() -> typing.Any:
    ...

def CryptBinaryToString() -> typing.Any:
    ...

def CryptDecodeMessage() -> typing.Any:
    ...

def CryptDecodeObjectEx() -> typing.Any:
    ...

def CryptDecryptAndVerifyMessageSignature() -> typing.Any:
    ...

def CryptDecryptMessage() -> typing.Any:
    ...

def CryptEncodeObjectEx() -> typing.Any:
    ...

def CryptEncryptMessage() -> typing.Any:
    ...

def CryptEnumKeyIdentifierProperties() -> typing.Any:
    ...

def CryptEnumOIDInfo() -> typing.Any:
    ...

def CryptEnumProviderTypes() -> typing.Any:
    ...

def CryptEnumProviders() -> typing.Any:
    ...

def CryptFindLocalizedName() -> typing.Any:
    ...

def CryptFindOIDInfo() -> typing.Any:
    ...

def CryptFormatObject() -> typing.Any:
    ...

def CryptGetDefaultProvider() -> typing.Any:
    ...

def CryptGetKeyIdentifierProperty() -> typing.Any:
    ...

def CryptGetMessageCertificates() -> typing.Any:
    ...

def CryptGetMessageSignerCount() -> typing.Any:
    ...

def CryptProtectData() -> typing.Any:
    ...

def CryptQueryObject() -> typing.Any:
    ...

def CryptSetProviderEx() -> typing.Any:
    ...

def CryptSignAndEncryptMessage() -> typing.Any:
    ...

def CryptSignMessage() -> typing.Any:
    ...

def CryptStringToBinary() -> typing.Any:
    ...

def CryptUnprotectData() -> typing.Any:
    ...

def CryptVerifyDetachedMessageSignature() -> typing.Any:
    ...

def CryptVerifyMessageSignature() -> typing.Any:
    ...

def PFXImportCertStore() -> typing.Any:
    ...

def PFXIsPFXBlob() -> typing.Any:
    ...

def PFXVerifyPassword() -> typing.Any:
    ...

__doc__: str
__file__: str
__name__: str
__package__: str
def __getattr__(name) -> typing.Any:
    ...

