# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: winxpgui, version: unspecified
# Module: winxpgui, version: unspecified

''

import typing
import builtins as _mod_builtins
from .lib import pywintypes as _mod_pywintypes

def AbortPath() -> typing.Any:
    ...

def AlphaBlend() -> typing.Any:
    ...

def AngleArc() -> typing.Any:
    ...

def AnimateWindow() -> typing.Any:
    ...

def AppendMenu() -> typing.Any:
    ...

def Arc() -> typing.Any:
    ...

def ArcTo() -> typing.Any:
    ...

def BeginPaint() -> typing.Any:
    ...

def BeginPath() -> typing.Any:
    ...

def BitBlt() -> typing.Any:
    ...

def BringWindowToTop() -> typing.Any:
    ...

CLR_NONE: int
def CallWindowProc() -> typing.Any:
    ...

def CheckMenuItem() -> typing.Any:
    ...

def CheckMenuRadioItem() -> typing.Any:
    ...

def ChildWindowFromPoint() -> typing.Any:
    ...

def ChildWindowFromPointEx() -> typing.Any:
    ...

def Chord() -> typing.Any:
    ...

def ClientToScreen() -> typing.Any:
    ...

def CloseFigure() -> typing.Any:
    ...

def CloseWindow() -> typing.Any:
    ...

def CombineRgn() -> typing.Any:
    ...

def CombineTransform() -> typing.Any:
    ...

def CommDlgExtendedError() -> typing.Any:
    ...

def CopyIcon() -> typing.Any:
    ...

def CreateAcceleratorTable() -> typing.Any:
    ...

def CreateBitmap() -> typing.Any:
    ...

def CreateBrushIndirect() -> typing.Any:
    ...

def CreateCaret() -> typing.Any:
    ...

def CreateCompatibleBitmap() -> typing.Any:
    ...

def CreateCompatibleDC() -> typing.Any:
    ...

def CreateDC() -> typing.Any:
    ...

def CreateDialogIndirect() -> typing.Any:
    ...

def CreateDialogIndirectParam() -> typing.Any:
    ...

def CreateEllipticRgnIndirect() -> typing.Any:
    ...

def CreateFontIndirect() -> typing.Any:
    ...

def CreateHatchBrush() -> typing.Any:
    ...

def CreateIconFromResource() -> typing.Any:
    ...

def CreateIconIndirect() -> typing.Any:
    ...

def CreateMenu() -> typing.Any:
    ...

def CreatePatternBrush() -> typing.Any:
    ...

def CreatePen() -> typing.Any:
    ...

def CreatePolygonRgn() -> typing.Any:
    ...

def CreatePopupMenu() -> typing.Any:
    ...

def CreateRectRgnIndirect() -> typing.Any:
    ...

def CreateRoundRectRgn() -> typing.Any:
    ...

def CreateSolidBrush() -> typing.Any:
    ...

def CreateWindow() -> typing.Any:
    ...

def CreateWindowEx() -> typing.Any:
    ...

def DefWindowProc() -> typing.Any:
    ...

def DeleteDC() -> typing.Any:
    ...

def DeleteMenu() -> typing.Any:
    ...

def DeleteObject() -> typing.Any:
    ...

def DestroyAcceleratorTable() -> typing.Any:
    ...

def DestroyCaret() -> typing.Any:
    ...

def DestroyIcon() -> typing.Any:
    ...

def DestroyMenu() -> typing.Any:
    ...

def DestroyWindow() -> typing.Any:
    ...

def DialogBox() -> typing.Any:
    ...

def DialogBoxIndirect() -> typing.Any:
    ...

def DialogBoxIndirectParam() -> typing.Any:
    ...

def DialogBoxParam() -> typing.Any:
    ...

def DispatchMessage() -> typing.Any:
    ...

def DragAcceptFiles() -> typing.Any:
    ...

def DragDetect() -> typing.Any:
    ...

def DrawAnimatedRects() -> typing.Any:
    ...

def DrawEdge() -> typing.Any:
    ...

def DrawFocusRect() -> typing.Any:
    ...

def DrawIcon() -> typing.Any:
    ...

def DrawIconEx() -> typing.Any:
    ...

def DrawMenuBar() -> typing.Any:
    ...

def DrawText() -> typing.Any:
    ...

def DrawTextW() -> typing.Any:
    ...

def Edit_GetLine() -> typing.Any:
    ...

def Ellipse() -> typing.Any:
    ...

def EnableMenuItem() -> typing.Any:
    ...

def EnableWindow() -> typing.Any:
    ...

def EndDialog() -> typing.Any:
    ...

def EndPaint() -> typing.Any:
    ...

def EndPath() -> typing.Any:
    ...

def EnumChildWindows() -> typing.Any:
    ...

def EnumFontFamilies() -> typing.Any:
    ...

def EnumPropsEx() -> typing.Any:
    ...

def EnumThreadWindows() -> typing.Any:
    ...

def EnumWindows() -> typing.Any:
    ...

def EqualRgn() -> typing.Any:
    ...

def ExtCreatePen() -> typing.Any:
    ...

def ExtFloodFill() -> typing.Any:
    ...

def ExtTextOut() -> typing.Any:
    ...

def ExtractIcon() -> typing.Any:
    ...

def ExtractIconEx() -> typing.Any:
    ...

def FillPath() -> typing.Any:
    ...

def FillRect() -> typing.Any:
    ...

def FillRgn() -> typing.Any:
    ...

def FindWindow() -> typing.Any:
    ...

def FindWindowEx() -> typing.Any:
    ...

def FlashWindow() -> typing.Any:
    ...

def FlashWindowEx() -> typing.Any:
    ...

def FlattenPath() -> typing.Any:
    ...

def FrameRect() -> typing.Any:
    ...

def FrameRgn() -> typing.Any:
    ...

def GetActiveWindow() -> typing.Any:
    ...

def GetArcDirection() -> typing.Any:
    ...

def GetBkColor() -> typing.Any:
    ...

def GetBkMode() -> typing.Any:
    ...

def GetCapture() -> typing.Any:
    ...

def GetCaretPos() -> typing.Any:
    ...

def GetClassLong() -> typing.Any:
    ...

def GetClassName() -> typing.Any:
    ...

def GetClientRect() -> typing.Any:
    ...

def GetConsoleWindow() -> typing.Any:
    ...

def GetCurrentObject() -> typing.Any:
    ...

def GetCurrentPositionEx() -> typing.Any:
    ...

def GetCursor() -> typing.Any:
    ...

def GetCursorInfo() -> typing.Any:
    ...

def GetCursorPos() -> typing.Any:
    ...

def GetDC() -> typing.Any:
    ...

def GetDesktopWindow() -> typing.Any:
    ...

def GetDlgCtrlID() -> typing.Any:
    ...

def GetDlgItem() -> typing.Any:
    ...

def GetDlgItemInt() -> typing.Any:
    ...

def GetDlgItemText() -> typing.Any:
    ...

def GetDoubleClickTime() -> typing.Any:
    ...

def GetFocus() -> typing.Any:
    ...

def GetForegroundWindow() -> typing.Any:
    ...

def GetGraphicsMode() -> typing.Any:
    ...

def GetIconInfo() -> typing.Any:
    ...

def GetLayeredWindowAttributes() -> typing.Any:
    ...

def GetLayout() -> typing.Any:
    ...

def GetMapMode() -> typing.Any:
    ...

def GetMenu() -> typing.Any:
    ...

def GetMenuDefaultItem() -> typing.Any:
    ...

def GetMenuInfo() -> typing.Any:
    ...

def GetMenuItemCount() -> typing.Any:
    ...

def GetMenuItemID() -> typing.Any:
    ...

def GetMenuItemInfo() -> typing.Any:
    ...

def GetMenuItemRect() -> typing.Any:
    ...

def GetMenuState() -> typing.Any:
    ...

def GetMessage() -> typing.Any:
    ...

def GetMiterLimit() -> typing.Any:
    ...

def GetModuleHandle() -> typing.Any:
    ...

def GetNextDlgGroupItem() -> typing.Any:
    ...

def GetNextDlgTabItem() -> typing.Any:
    ...

def GetObject() -> typing.Any:
    ...

def GetObjectType() -> typing.Any:
    ...

def GetOpenFileName() -> typing.Any:
    ...

def GetOpenFileNameW() -> typing.Any:
    ...

def GetParent() -> typing.Any:
    ...

def GetPath() -> typing.Any:
    ...

def GetPixel() -> typing.Any:
    ...

def GetPolyFillMode() -> typing.Any:
    ...

def GetROP2() -> typing.Any:
    ...

def GetRgnBox() -> typing.Any:
    ...

def GetSaveFileNameW() -> typing.Any:
    ...

def GetScrollInfo() -> typing.Any:
    ...

def GetStockObject() -> typing.Any:
    ...

def GetStretchBltMode() -> typing.Any:
    ...

def GetSubMenu() -> typing.Any:
    ...

def GetSysColor() -> typing.Any:
    ...

def GetSysColorBrush() -> typing.Any:
    ...

def GetSystemMenu() -> typing.Any:
    ...

def GetTextAlign() -> typing.Any:
    ...

def GetTextCharacterExtra() -> typing.Any:
    ...

def GetTextColor() -> typing.Any:
    ...

def GetTextExtentPoint32() -> typing.Any:
    ...

def GetTextFace() -> typing.Any:
    ...

def GetTextMetrics() -> typing.Any:
    ...

def GetUpdateRgn() -> typing.Any:
    ...

def GetViewportExtEx() -> typing.Any:
    ...

def GetViewportOrgEx() -> typing.Any:
    ...

def GetWindow() -> typing.Any:
    ...

def GetWindowDC() -> typing.Any:
    ...

def GetWindowExtEx() -> typing.Any:
    ...

def GetWindowLong() -> typing.Any:
    ...

def GetWindowOrgEx() -> typing.Any:
    ...

def GetWindowPlacement() -> typing.Any:
    ...

def GetWindowRect() -> typing.Any:
    ...

def GetWindowRgn() -> typing.Any:
    ...

def GetWindowRgnBox() -> typing.Any:
    ...

def GetWindowText() -> typing.Any:
    ...

def GetWindowTextLength() -> typing.Any:
    ...

def GetWorldTransform() -> typing.Any:
    ...

def GradientFill() -> typing.Any:
    ...

def HIWORD() -> typing.Any:
    ...

def HideCaret() -> typing.Any:
    ...

ILC_COLOR: int
ILC_COLOR16: int
ILC_COLOR24: int
ILC_COLOR32: int
ILC_COLOR4: int
ILC_COLOR8: int
ILC_COLORDDB: int
ILC_MASK: int
ILD_BLEND: int
ILD_BLEND25: int
ILD_BLEND50: int
ILD_FOCUS: int
ILD_MASK: int
ILD_NORMAL: int
ILD_SELECTED: int
ILD_TRANSPARENT: int
IMAGE_BITMAP: int
IMAGE_CURSOR: int
IMAGE_ICON: int
def ImageList_Add() -> typing.Any:
    ...

def ImageList_Create() -> typing.Any:
    ...

def ImageList_Destroy() -> typing.Any:
    ...

def ImageList_Draw() -> typing.Any:
    ...

def ImageList_DrawEx() -> typing.Any:
    ...

def ImageList_GetIcon() -> typing.Any:
    ...

def ImageList_GetImageCount() -> typing.Any:
    ...

def ImageList_LoadBitmap() -> typing.Any:
    ...

def ImageList_LoadImage() -> typing.Any:
    ...

def ImageList_Remove() -> typing.Any:
    ...

def ImageList_Replace() -> typing.Any:
    ...

def ImageList_ReplaceIcon() -> typing.Any:
    ...

def ImageList_SetBkColor() -> typing.Any:
    ...

def ImageList_SetOverlayImage() -> typing.Any:
    ...

def InitCommonControls() -> typing.Any:
    ...

def InitCommonControlsEx() -> typing.Any:
    ...

def InsertMenu() -> typing.Any:
    ...

def InsertMenuItem() -> typing.Any:
    ...

def InvalidateRect() -> typing.Any:
    ...

def InvalidateRgn() -> typing.Any:
    ...

def InvertRect() -> typing.Any:
    ...

def InvertRgn() -> typing.Any:
    ...

def IsChild() -> typing.Any:
    ...

def IsIconic() -> typing.Any:
    ...

def IsWindow() -> typing.Any:
    ...

def IsWindowEnabled() -> typing.Any:
    ...

def IsWindowVisible() -> typing.Any:
    ...

def LOGFONT() -> typing.Any:
    ...

def LOWORD() -> typing.Any:
    ...

LR_CREATEDIBSECTION: int
LR_DEFAULTCOLOR: int
LR_DEFAULTSIZE: int
LR_LOADFROMFILE: int
LR_LOADMAP3DCOLORS: int
LR_LOADTRANSPARENT: int
LR_MONOCHROME: int
LR_SHARED: int
LR_VGACOLOR: int
def LineTo() -> typing.Any:
    ...

def ListView_SortItems() -> typing.Any:
    ...

def ListView_SortItemsEx() -> typing.Any:
    ...

def LoadCursor() -> typing.Any:
    ...

def LoadIcon() -> typing.Any:
    ...

def LoadImage() -> typing.Any:
    ...

def LoadMenu() -> typing.Any:
    ...

def MaskBlt() -> typing.Any:
    ...

def MessageBeep() -> typing.Any:
    ...

def MessageBox() -> typing.Any:
    ...

def ModifyMenu() -> typing.Any:
    ...

def ModifyWorldTransform() -> typing.Any:
    ...

def MoveToEx() -> typing.Any:
    ...

def MoveWindow() -> typing.Any:
    ...

NIF_ICON: int
NIF_INFO: int
NIF_MESSAGE: int
NIF_STATE: int
NIF_TIP: int
NIIF_ERROR: int
NIIF_ICON_MASK: int
NIIF_INFO: int
NIIF_NONE: int
NIIF_NOSOUND: int
NIIF_WARNING: int
NIM_ADD: int
NIM_DELETE: int
NIM_MODIFY: int
NIM_SETVERSION: int
def OffsetRgn() -> typing.Any:
    ...

def PaintDesktop() -> typing.Any:
    ...

def PaintRgn() -> typing.Any:
    ...

def PatBlt() -> typing.Any:
    ...

def PathToRegion() -> typing.Any:
    ...

def PeekMessage() -> typing.Any:
    ...

def Pie() -> typing.Any:
    ...

def PlgBlt() -> typing.Any:
    ...

def PolyBezier() -> typing.Any:
    ...

def PolyBezierTo() -> typing.Any:
    ...

def Polygon() -> typing.Any:
    ...

def Polyline() -> typing.Any:
    ...

def PolylineTo() -> typing.Any:
    ...

def PostMessage() -> typing.Any:
    ...

def PostQuitMessage() -> typing.Any:
    ...

def PostThreadMessage() -> typing.Any:
    ...

def PtInRect() -> typing.Any:
    ...

def PtInRegion() -> typing.Any:
    ...

def PumpMessages() -> typing.Any:
    ...

def PumpWaitingMessages() -> typing.Any:
    ...

def PyGetArraySignedLong() -> typing.Any:
    ...

def PyGetBufferAddressAndLen() -> typing.Any:
    ...

def PyGetMemory() -> typing.Any:
    ...

def PyGetString() -> typing.Any:
    ...

def PyMakeBuffer() -> typing.Any:
    ...

def PySetMemory() -> typing.Any:
    ...

def PySetString() -> typing.Any:
    ...

def RectInRegion() -> typing.Any:
    ...

def Rectangle() -> typing.Any:
    ...

def RedrawWindow() -> typing.Any:
    ...

def RegisterClass() -> typing.Any:
    ...

def RegisterDeviceNotification() -> typing.Any:
    ...

def RegisterHotKey() -> typing.Any:
    ...

def RegisterWindowMessage() -> typing.Any:
    ...

def ReleaseCapture() -> typing.Any:
    ...

def ReleaseDC() -> typing.Any:
    ...

def RemoveMenu() -> typing.Any:
    ...

def ReplyMessage() -> typing.Any:
    ...

def RestoreDC() -> typing.Any:
    ...

def RoundRect() -> typing.Any:
    ...

def SaveDC() -> typing.Any:
    ...

def ScreenToClient() -> typing.Any:
    ...

def ScrollWindowEx() -> typing.Any:
    ...

def SelectObject() -> typing.Any:
    ...

def SendMessage() -> typing.Any:
    ...

def SendMessageTimeout() -> typing.Any:
    ...

def SetActiveWindow() -> typing.Any:
    ...

def SetArcDirection() -> typing.Any:
    ...

def SetBkColor() -> typing.Any:
    ...

def SetBkMode() -> typing.Any:
    ...

def SetCapture() -> typing.Any:
    ...

def SetCaretPos() -> typing.Any:
    ...

def SetCursor() -> typing.Any:
    ...

def SetDlgItemInt() -> typing.Any:
    ...

def SetDlgItemText() -> typing.Any:
    ...

def SetDoubleClickTime() -> typing.Any:
    ...

def SetFocus() -> typing.Any:
    ...

def SetForegroundWindow() -> typing.Any:
    ...

def SetGraphicsMode() -> typing.Any:
    ...

def SetLayeredWindowAttributes() -> typing.Any:
    ...

def SetLayout() -> typing.Any:
    ...

def SetMapMode() -> typing.Any:
    ...

def SetMenu() -> typing.Any:
    ...

def SetMenuDefaultItem() -> typing.Any:
    ...

def SetMenuInfo() -> typing.Any:
    ...

def SetMenuItemBitmaps() -> typing.Any:
    ...

def SetMenuItemInfo() -> typing.Any:
    ...

def SetMiterLimit() -> typing.Any:
    ...

def SetParent() -> typing.Any:
    ...

def SetPixel() -> typing.Any:
    ...

def SetPixelV() -> typing.Any:
    ...

def SetPolyFillMode() -> typing.Any:
    ...

def SetROP2() -> typing.Any:
    ...

def SetRectRgn() -> typing.Any:
    ...

def SetScrollInfo() -> typing.Any:
    ...

def SetStretchBltMode() -> typing.Any:
    ...

def SetTextAlign() -> typing.Any:
    ...

def SetTextCharacterExtra() -> typing.Any:
    ...

def SetTextColor() -> typing.Any:
    ...

def SetViewportExtEx() -> typing.Any:
    ...

def SetViewportOrgEx() -> typing.Any:
    ...

def SetWindowExtEx() -> typing.Any:
    ...

def SetWindowLong() -> typing.Any:
    ...

def SetWindowOrgEx() -> typing.Any:
    ...

def SetWindowPlacement() -> typing.Any:
    ...

def SetWindowPos() -> typing.Any:
    ...

def SetWindowRgn() -> typing.Any:
    ...

def SetWindowText() -> typing.Any:
    ...

def SetWorldTransform() -> typing.Any:
    ...

def Shell_NotifyIcon() -> typing.Any:
    ...

def ShowCaret() -> typing.Any:
    ...

def ShowWindow() -> typing.Any:
    ...

def StretchBlt() -> typing.Any:
    ...

def StrokeAndFillPath() -> typing.Any:
    ...

def StrokePath() -> typing.Any:
    ...

def SystemParametersInfo() -> typing.Any:
    ...

TPM_BOTTOMALIGN: int
TPM_CENTERALIGN: int
TPM_LEFTALIGN: int
TPM_LEFTBUTTON: int
TPM_NONOTIFY: int
TPM_RETURNCMD: int
TPM_RIGHTALIGN: int
TPM_RIGHTBUTTON: int
TPM_TOPALIGN: int
TPM_VCENTERALIGN: int
def TrackPopupMenu() -> typing.Any:
    ...

def TranslateAccelerator() -> typing.Any:
    ...

def TranslateMessage() -> typing.Any:
    ...

def TransparentBlt() -> typing.Any:
    ...

UNICODE: bool
def UnregisterClass() -> typing.Any:
    ...

def UnregisterDeviceNotification() -> typing.Any:
    ...

def UpdateLayeredWindow() -> typing.Any:
    ...

def UpdateWindow() -> typing.Any:
    ...

def ValidateRect() -> typing.Any:
    ...

def ValidateRgn() -> typing.Any:
    ...

def WNDCLASS() -> typing.Any:
    ...

def WaitMessage() -> typing.Any:
    ...

def WidenPath() -> typing.Any:
    ...

def WindowFromDC() -> typing.Any:
    ...

def WindowFromPoint() -> typing.Any:
    ...

def _TrackMouseEvent() -> typing.Any:
    ...

__doc__: str
__file__: str
__name__: str
__package__: str
dllhandle: int
error = _mod_pywintypes.error
def lpstr() -> typing.Any:
    ...

def set_logger() -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

