from pandas._typing import FilePathOrBuffer as FilePathOrBuffer
from pandas.core.frame import DataFrame as DataFrame
#    , get_option as get_option
#from pandas.compat._optional import import_optional_dependency as import_optional_dependency
#from pandas.errors import AbstractMethodError as AbstractMethodError
#from pandas.io.common import get_filepath_or_buffer as get_filepath_or_buffer, is_gcs_url as is_gcs_url, is_s3_url as is_s3_url
from typing import Any, Optional, Sequence

def get_engine(engine: str) -> BaseImpl: ...

class BaseImpl:
    @staticmethod
    def validate_dataframe(df: DataFrame) -> Any: ...
    def write(self, df: DataFrame, path: Any, compression: Any, **kwargs: Any) -> Any: ...
    def read(self, path: Any, columns: Optional[Any] = ..., **kwargs: Any) -> None: ...

class PyArrowImpl(BaseImpl):
    api: Any = ...
    def __init__(self) -> None: ...
    def write(self, df: DataFrame, path: Any, compression: Any=..., coerce_timestamps: Any=..., index: Optional[bool]=..., partition_cols: Any=..., **kwargs: Any) -> Any: ...
    def read(self, path: Any, columns: Optional[Any] = ..., **kwargs: Any): ...

class FastParquetImpl(BaseImpl):
    api: Any = ...
    def __init__(self) -> None: ...
    def write(self, df: DataFrame, path: Any, compression: Any=..., index: Any=..., partition_cols: Any=..., **kwargs: Any) -> Any: ...
    def read(self, path: Any, columns: Optional[Any] = ..., **kwargs: Any): ...

def to_parquet(df: DataFrame, path: Any, engine: str=..., compression: Any=..., index: Optional[bool]=..., partition_cols: Any=..., **kwargs: Any) -> Any: ...
def read_parquet(
    path: FilePathOrBuffer, engine: str = ..., columns: Optional[Sequence[str]] = ..., **kwargs
) -> DataFrame: ...
