from pandas.tseries.offsets import DateOffset as DateOffset
from typing import Optional

def get_period_alias(offset_str: str) -> Optional[str]: ...
def to_offset(freq) -> Optional[DateOffset]: ...
def get_offset(name: str) -> DateOffset: ...
def infer_freq(index, warn: bool=...) -> Optional[str]: ...

class _FrequencyInferer:
    index = ...
    values = ...
    warn = ...
    is_monotonic = ...
    def __init__(self, index, warn: bool=...) -> None: ...
    def deltas(self): ...
    def deltas_asi8(self): ...
    def is_unique(self) -> bool: ...
    def is_unique_asi8(self): ...
    def get_freq(self) -> Optional[str]: ...
    def day_deltas(self): ...
    def hour_deltas(self): ...
    def fields(self): ...
    def rep_stamp(self): ...
    def month_position_check(self): ...
    def mdiffs(self): ...
    def ydiffs(self): ...

class _TimedeltaFrequencyInferer(_FrequencyInferer): ...
