from .. import Provider as SsnProvider
from typing import Any, Optional

def checksum(digits: Any, scale: Any): ...

class Provider(SsnProvider):
    scale1: Any = ...
    scale2: Any = ...
    def ssn(self, dob: Optional[Any] = ..., gender: Optional[Any] = ...): ...
