from .. import Provider as AddressProvider
from typing import Any

class Provider(AddressProvider):
    street_suffixes: Any = ...
    street_name_formats: Any = ...
    city_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    frequent_street_names: Any = ...
    real_city_names: Any = ...
    city_prefs: Any = ...
    city_parts: Any = ...
    city_suffixes: Any = ...
    counties: Any = ...
    countries: Any = ...
    def county(self): ...
    def street_address_with_county(self): ...
    def city_prefix(self): ...
    def city_part(self): ...
    def real_city_name(self): ...
    def frequent_street_name(self): ...
    def postcode(self): ...
    def street_name(self): ...
    def building_number(self): ...
