from ..classes.graph import Graph

__all__ = ["efficiency", "local_efficiency", "global_efficiency"]

def efficiency(G: Graph, u, v) -> float: ...
def global_efficiency(G: Graph) -> float: ...
def local_efficiency(G: Graph) -> float: ...
