from typing import Any

from .. import Provider as PhoneNumberProvider

class Provider(PhoneNumberProvider):
    formats: Any = ...
    area_codes: Any = ...
    def area_code(self): ...
    def phone_number(self): ...
