from contextlib import contextmanager
from typing import Any, Generator

_default_config = ...
_current_config = ...
@contextmanager
def using(**kwargs) -> Generator[None, Any, None]:
    ...

def setup(key, value=...) -> None:
    ...

def query(key):
    ...

def configure() -> None:
    ...

