from .. import Provider as DateTimeProvider
from typing import Any

class Provider(DateTimeProvider):
    DAY_NAMES: Any = ...
    MONTH_NAMES: Any = ...
    centuries: Any = ...
    countries: Any = ...
    AM_PM: Any = ...
    def month_name(self): ...
    def am_pm(self): ...
    def day_of_week(self): ...
