from .. import Provider as CompanyProvider
from typing import Any

class Provider(CompanyProvider):
    formats: Any = ...
    catch_phrase_formats: Any = ...
    nouns: Any = ...
    verbs: Any = ...
    attributes: Any = ...
    company_suffixes: Any = ...
