from .. import Provider as AddressProvider
from typing import Any

class Provider(AddressProvider):
    address_formats: Any = ...
    building_number_formats: Any = ...
    countries: Any = ...
    prefectures: Any = ...
    cities: Any = ...
    towns: Any = ...
    building_names: Any = ...
    def prefecture(self): ...
    def city(self): ...
    def town(self): ...
    def chome(self): ...
    def ban(self): ...
    def gou(self): ...
    def building_name(self): ...
    def postcode(self): ...
    def zipcode(self): ...
