from typing import Any

from .. import Provider as PhoneNumberProvider

class Provider(PhoneNumberProvider):
    cellphone_formats: Any = ...
    telephone_formats: Any = ...
    services_phones_formats: Any = ...
    formats: Any = ...
    def operator_id(self): ...
    def area_code(self): ...
    def cellphone_number(self): ...
    def telephone_number(self): ...
    def service_phone_number(self): ...
    def phone_number(self): ...
