from typing import Any

from ..la import Provider as LoremProvider

class Provider(LoremProvider):
    english_word_list: Any = ...
    def english_word(self): ...
    def english_words(self, nb: int = ..., unique: bool = ...): ...
    def english_sentence(self, nb_words: int = ..., variable_nb_words: bool = ...): ...
    def english_sentences(self, nb: int = ...): ...
    def english_paragraph(
        self, nb_sentences: int = ..., variable_nb_sentences: bool = ...
    ): ...
    def english_paragraphs(self, nb: int = ...): ...
    def english_text(self, max_nb_chars: int = ...): ...
    def english_texts(self, nb_texts: int = ..., max_nb_chars: int = ...): ...
