from typing import Any

from .. import Provider as SsnProvider

ALPHANUMERICS: Any
ALPHANUMERICS_DICT: Any
CHECKSUM_TABLE: Any

def checksum(value: Any): ...

class Provider(SsnProvider):
    fiscal_code_format: str = ...
    def ssn(self): ...
    vat_id_formats: Any = ...
    def vat_id(self): ...
