from typing import Any

from .. import Provider as CompanyProvider

class Provider(CompanyProvider):
    formats: Any = ...
    catch_phrase_formats: Any = ...
    nouns: Any = ...
    verbs: Any = ...
    attributes: Any = ...
    company_suffixes: Any = ...
    siren_format: str = ...
    def catch_phrase_noun(self): ...
    def catch_phrase_attribute(self): ...
    def catch_phrase_verb(self): ...
    def catch_phrase(self): ...
    words_which_should_not_appear_twice: Any = ...
    def siren(self): ...
    def siret(self, max_sequential_digits: int = ...): ...
