from pandas.core.window.common import WindowGroupByMixin as WindowGroupByMixin
from pandas.core.window.rolling import _Rolling_and_Expanding

class Expanding(_Rolling_and_Expanding):
    def __init__(self, obj, min_periods: int = ..., center: bool = ..., axis: int = ..., **kwargs) -> None: ...
    def aggregate(self, func, *args, **kwargs): ...
    agg = ...
    def count(self, **kwargs): ...
    def apply(self, func, raw: bool = ..., args = ..., kwargs = ...): ...
    def sum(self, *args, **kwargs): ...
    def max(self, *args, **kwargs): ...
    def min(self, *args, **kwargs): ...
    def mean(self, *args, **kwargs): ...
    def median(self, **kwargs): ...
    def std(self, ddof: int = ..., *args, **kwargs): ...
    def var(self, ddof: int = ..., *args, **kwargs): ...
    def skew(self, **kwargs): ...
    def kurt(self, **kwargs): ...
    def quantile(self, quantile, interpolation: str = ..., **kwargs): ...
    def cov(self, other = ..., pairwise = ..., ddof: int = ..., **kwargs): ...
    def corr(self, other = ..., pairwise = ..., **kwargs): ...

class ExpandingGroupby(WindowGroupByMixin, Expanding): ...
