from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    city_suffixes: Any = ...
    city_formats: Any = ...
    district_formats: Any = ...
    building_number_formats: Any = ...
    postcode_formats: Any = ...
    street_suffixes: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    provinces: Any = ...
    districts: Any = ...
    cities: Any = ...
    countries: Any = ...
    def building_number(self): ...
    def city_name(self): ...
    def province(self): ...
    def district(self): ...
