from ... import BaseProvider as BaseProvider
from typing import Any

class Provider(BaseProvider):
    sss_formats: Any = ...
    gsis_formats: Any = ...
    philhealth_formats: Any = ...
    pagibig_formats: Any = ...
    umid_formats: Any = ...
    def sss(self): ...
    def gsis(self): ...
    def pagibig(self): ...
    def philhealth(self): ...
    def umid(self): ...
    def ssn(self): ...
