from numpy import ndarray
from typing import Any, List, Union

class Bunch(dict):
    def __init__(self, **kwargs) -> None: ...
    def __setattr__(self, key: str, value: Union[ndarray, List[str], str]) -> None: ...
    def __dir__(self): ...
    def __getattr__(self, key: str) -> Any: ...
    def __setstate__(self, state): ...
