from .. import BaseProvider as BaseProvider
from typing import Any, Optional

localized: bool
default_locale: str

class Provider(BaseProvider):
    word_connector: str = ...
    sentence_punctuation: str = ...
    def words(
        self, nb: int = ..., ext_word_list: Optional[Any] = ..., unique: bool = ...
    ): ...
    def word(self, ext_word_list: Optional[Any] = ...): ...
    def sentence(
        self,
        nb_words: int = ...,
        variable_nb_words: bool = ...,
        ext_word_list: Optional[Any] = ...,
    ): ...
    def sentences(self, nb: int = ..., ext_word_list: Optional[Any] = ...): ...
    def paragraph(
        self,
        nb_sentences: int = ...,
        variable_nb_sentences: bool = ...,
        ext_word_list: Optional[Any] = ...,
    ): ...
    def paragraphs(self, nb: int = ..., ext_word_list: Optional[Any] = ...): ...
    def text(self, max_nb_chars: int = ..., ext_word_list: Optional[Any] = ...): ...
    def texts(
        self,
        nb_texts: int = ...,
        max_nb_chars: int = ...,
        ext_word_list: Optional[Any] = ...,
    ): ...
