import datetime
import numpy as np
from typing import Any, Callable, Iterable, Literal, Sequence
from matplotlib._typing import *
from matplotlib.figure import Figure
from matplotlib.transforms import Bbox
from matplotlib.axes import Axes

"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""

def do_constrained_layout(
    fig: Figure,
    h_pad: float,
    w_pad: float,
    hspace: float = ...,
    wspace: float = ...,
    rect: tuple = ...,
    compress: bool = ...,
):
    """
    Do the constrained_layout.  Called at draw time in
     ``figure.constrained_layout()``

    Parameters
    ----------
    fig : Figure
        ``Figure`` instance to do the layout in.

    renderer : Renderer
        Renderer to use.

    h_pad, w_pad : float
      Padding around the axes elements in figure-normalized units.

    hspace, wspace : float
       Fraction of the figure to dedicate to space between the
       axes.  These are evenly spread between the gaps between the axes.
       A value of 0.2 for a three-column layout would have a space
       of 0.1 of the figure width between each column.
       If h/wspace < h/w_pad, then the pads are used instead.

    rect : tuple of 4 floats
        Rectangle in figure coordinates to perform constrained layout in
        [left, bottom, width, height], each from 0-1.

    compress : bool
        Whether to shift Axes so that white space in between them is
        removed. This is useful for simple grids of fixed-aspect Axes (e.g.
        a grid of images).

    Returns
    -------
    layoutgrid : private debugging structure
    """
    ...

def make_layoutgrids(fig, layoutgrids, rect=...):
    """
    Make the layoutgrid tree.

    (Sub)Figures get a layoutgrid so we can have figure margins.

    Gridspecs that are attached to axes get a layoutgrid so axes
    can have margins.
    """
    ...

def make_layoutgrids_gs(layoutgrids, gs):
    """
    Make the layoutgrid for a gridspec (and anything nested in the gridspec)
    """
    ...

def check_no_collapsed_axes(layoutgrids, fig):
    """
    Check that no axes have collapsed to zero size.
    """
    ...

def compress_fixed_aspect(layoutgrids, fig): ...
def get_margin_from_padding(obj, *, w_pad=..., h_pad=..., hspace=..., wspace=...): ...
def make_layout_margins(
    layoutgrids, fig, renderer, *, w_pad=..., h_pad=..., hspace=..., wspace=...
):
    """
    For each axes, make a margin between the *pos* layoutbox and the
    *axes* layoutbox be a minimum size that can accommodate the
    decorations on the axis.

    Then make room for colorbars.
    """
    ...

def make_margin_suptitles(layoutgrids, fig, renderer, *, w_pad=..., h_pad=...): ...
def match_submerged_margins(layoutgrids, fig):
    """
    Make the margins that are submerged inside an Axes the same size.

    This allows axes that span two columns (or rows) that are offset
    from one another to have the same size.

    This gives the proper layout for something like::
        fig = plt.figure(constrained_layout=True)
        axs = fig.subplot_mosaic("AAAB\nCCDD")

    Without this routine, the axes D will be wider than C, because the
    margin width between the two columns in C has no width by default,
    whereas the margins between the two columns of D are set by the
    width of the margin between A and B. However, obviously the user would
    like C and D to be the same size, so we need to add constraints to these
    "submerged" margins.

    This routine makes all the interior margins the same, and the spacing
    between the three columns in A and the two column in C are all set to the
    margins between the two columns of D.

    See test_constrained_layout::test_constrained_layout12 for an example.
    """
    ...

def get_cb_parent_spans(cbax):
    """
    Figure out which subplotspecs this colorbar belongs to:
    """
    ...

def get_pos_and_bbox(ax, renderer):
    """
    Get the position and the bbox for the axes.

    Parameters
    ----------
    ax
    renderer

    Returns
    -------
    pos : Bbox
        Position in figure coordinates.
    bbox : Bbox
        Tight bounding box in figure coordinates.
    """
    ...

def reposition_axes(
    layoutgrids, fig, renderer, *, w_pad=..., h_pad=..., hspace=..., wspace=...
):
    """
    Reposition all the axes based on the new inner bounding box.
    """
    ...

def reposition_colorbar(layoutgrids, cbax: Axes, renderer, *, offset=...):
    """
    Place the colorbar in its new place.

    Parameters
    ----------
    cbax : Axes
        Axes for the colorbar

    renderer :
    w_pad, h_pad : float
        width and height padding (in fraction of figure)
    hspace, wspace : float
        width and height padding as fraction of figure size divided by
        number of  columns or rows
    margin : array-like
        offset the colorbar needs to be pushed to in order to
        account for multiple colorbars
    """
    ...

def reset_margins(layoutgrids, fig):
    """
    Reset the margins in the layoutboxes of fig.

    Margins are usually set as a minimum, so if the figure gets smaller
    the minimum needs to be zero in order for it to grow again.
    """
    ...

def colorbar_get_pad(layoutgrids, cax): ...
