from enum import Enum

class _AutoStringNameEnum(Enum):
    def __hash__(self) -> int: ...

class JoinStyle(str, _AutoStringNameEnum):

    miter = ...
    round = ...
    bevel = ...
    @staticmethod
    def demo() -> None: ...

class CapStyle(str, _AutoStringNameEnum):
    butt = ...
    projecting = ...
    round = ...
    @staticmethod
    def demo() -> None: ...
