import datetime
import numpy as np
from typing import Any, Callable, Iterable, Literal, Sequence
from matplotlib._typing import *
from matplotlib.gridspec import SubplotSpec

"""
This type stub file was generated by pyright.
"""
from typing import List, Optional, Tuple, Union

"""
This type stub file was generated by pyright.
"""

class LayoutGrid:
    """
    Analogous to a gridspec, and contained in another LayoutGrid.
    """

    def __init__(
        self,
        parent: Union[LayoutGrid, Tuple[int, int, int, int]] = ...,
        parent_pos: Union[Tuple[range, range], Tuple[int, int]] = ...,
        parent_inner: bool = ...,
        name: str = ...,
        ncols: int = ...,
        nrows: int = ...,
        h_pad: None = ...,
        w_pad: None = ...,
        width_ratios: Optional[list[int]] = ...,
        height_ratios: Optional[Union[list[Union[int, float]], list[int]]] = ...,
    ) -> None: ...
    def __repr__(self): ...
    def reset_margins(self) -> None:
        """
        Reset all the margins to zero.  Must do this after changing
        figure size, for instance, because the relative size of the
        axes labels etc changes.
        """
        ...
    def add_constraints(self) -> None: ...
    def hard_constraints(self) -> None:
        """
        These are the redundant constraints, plus ones that make the
        rest of the code easier.
        """
        ...
    def add_child(
        self,
        child: "LayoutGrid",
        i: Union[int, range] = ...,
        j: Union[int, range] = ...,
    ) -> None: ...
    def parent_constraints(self) -> None: ...
    def grid_constraints(self) -> None: ...
    def edit_margin(self, todo: str, size: float, cell: int) -> None:
        """
        Change the size of the margin for one cell.

        Parameters
        ----------
        todo : string (one of 'left', 'right', 'bottom', 'top')
            margin to alter.

        size : float
            Size of the margin.  If it is larger than the existing minimum it
            updates the margin size. Fraction of figure size.

        cell : int
            Cell column or row to edit.
        """
        ...
    def edit_margin_min(
        self, todo: str, size: Union[int, float], cell: int = ...
    ) -> None:
        """
        Change the minimum size of the margin for one cell.

        Parameters
        ----------
        todo : string (one of 'left', 'right', 'bottom', 'top')
            margin to alter.

        size : float
            Minimum size of the margin .  If it is larger than the
            existing minimum it updates the margin size. Fraction of
            figure size.

        cell : int
            Cell column or row to edit.
        """
        ...
    def edit_margins(self, todo: str, size: float) -> None:
        """
        Change the size of all the margin of all the cells in the layout grid.

        Parameters
        ----------
        todo : string (one of 'left', 'right', 'bottom', 'top')
            margin to alter.

        size : float
            Size to set the margins.  Fraction of figure size.
        """
        ...
    def edit_all_margins_min(
        self, todo: Literal["left", "right", "bottom", "top"], size: float
    ):
        """
        Change the minimum size of all the margin of all
        the cells in the layout grid.

        Parameters
        ----------
        todo : {'left', 'right', 'bottom', 'top'}
            The margin to alter.

        size : float
            Minimum size of the margin.  If it is larger than the
            existing minimum it updates the margin size. Fraction of
            figure size.
        """
        ...
    def edit_outer_margin_mins(self, margin: dict, ss: SubplotSpec):
        """
        Edit all four margin minimums in one statement.

        Parameters
        ----------
        margin : dict
            size of margins in a dict with keys 'left', 'right', 'bottom',
            'top'

        ss : SubplotSpec
            defines the subplotspec these margins should be applied to
        """
        ...
    def get_margins(self, todo, col):
        """Return the margin at this position"""
        ...
    def get_outer_bbox(self, rows=..., cols=...):
        """
        Return the outer bounding box of the subplot specs
        given by rows and cols.  rows and cols can be spans.
        """
        ...
    def get_inner_bbox(self, rows=..., cols=...):
        """
        Return the inner bounding box of the subplot specs
        given by rows and cols.  rows and cols can be spans.
        """
        ...
    def get_bbox_for_cb(self, rows=..., cols=...):
        """
        Return the bounding box that includes the
        decorations but, *not* the colorbar...
        """
        ...
    def get_left_margin_bbox(self, rows=..., cols=...):
        """
        Return the left margin bounding box of the subplot specs
        given by rows and cols.  rows and cols can be spans.
        """
        ...
    def get_bottom_margin_bbox(self, rows=..., cols=...):
        """
        Return the left margin bounding box of the subplot specs
        given by rows and cols.  rows and cols can be spans.
        """
        ...
    def get_right_margin_bbox(self, rows=..., cols=...):
        """
        Return the left margin bounding box of the subplot specs
        given by rows and cols.  rows and cols can be spans.
        """
        ...
    def get_top_margin_bbox(self, rows=..., cols=...):
        """
        Return the left margin bounding box of the subplot specs
        given by rows and cols.  rows and cols can be spans.
        """
        ...
    def update_variables(self) -> None:
        """
        Update the variables for the solver attached to this layoutgrid.
        """
        ...

def seq_id() -> str:
    """Generate a short sequential id for layoutbox objects."""
    ...

def print_children(lb):
    """Print the children of the layoutbox."""
    ...

def plot_children(fig, lg=..., level=..., printit=...):
    """Simple plotting to show where boxes are."""
    ...
