from typing import Literal
from .gridspec import SubplotSpec
from .transforms import Bbox
from .figure import Figure

class LayoutGrid:
    def __init__(
        self,
        parent: LayoutGrid | tuple[int, int, int, int] = ...,
        parent_pos: tuple[range, range] | tuple[int, int] = ...,
        parent_inner: bool = ...,
        name: str = ...,
        ncols: int = ...,
        nrows: int = ...,
        h_pad: None = ...,
        w_pad: None = ...,
        width_ratios: None | list[float] = ...,
        height_ratios: None | list[float] = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def reset_margins(self) -> None: ...
    def add_constraints(self) -> None: ...
    def hard_constraints(self) -> None: ...
    def add_child(
        self,
        child: "LayoutGrid",
        i: int | range = ...,
        j: int | range = ...,
    ) -> None: ...
    def parent_constraints(self) -> None: ...
    def grid_constraints(self) -> None: ...
    def edit_margin(
        self, todo: Literal["left", "right", "bottom", "top"], size: float, cell: int
    ) -> None: ...
    def edit_margin_min(
        self,
        todo: Literal["left", "right", "bottom", "top"],
        size: float,
        cell: int = ...,
    ) -> None: ...
    def edit_margins(
        self, todo: Literal["left", "right", "bottom", "top"], size: float
    ) -> None: ...
    def edit_all_margins_min(
        self, todo: Literal["left", "right", "bottom", "top"], size: float
    ): ...
    def edit_outer_margin_mins(self, margin: dict, ss: SubplotSpec): ...
    def get_margins(self, todo, col) -> Bbox: ...
    def get_outer_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_inner_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_bbox_for_cb(self, rows=..., cols=...) -> Bbox: ...
    def get_left_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_bottom_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_right_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_top_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def update_variables(self) -> None: ...

def seq_id() -> str: ...
def print_children(lb) -> None: ...
def plot_children(fig: Figure, lg=..., level=..., printit=...): ...
