class InvalidRequirement(ValueError):
    """
    An invalid requirement was found, users should refer to PEP 508.
    """

    ...

class Requirement:
    """Parse a requirement.

    Parse a given requirement string into its parts, such as name, specifier,
    URL, and extras. Raises InvalidRequirement on a badly-formed requirement
    string.
    """

    name: str = ...
    url: str = ...
    extras: str = ...
    specifier: str = ...
    marker: str = ...
    def __init__(self, requirement_string: str) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

