class ProjectionRegistry:
    def __init__(self) -> None: ...
    def register(self, *projections): ...
    def get_projection_class(self, name): ...
    def get_projection_names(self): ...

projection_registry = ...

def register_projection(cls): ...
def get_projection_class(projection=...): ...

get_projection_names = ...
