from .. import BaseProvider as BaseProvider
from typing import Any

localized: bool

class Provider(BaseProvider):
    formats: Any = ...
    company_suffixes: Any = ...
    catch_phrase_words: Any = ...
    bsWords: Any = ...
    def company(self): ...
    def company_suffix(self): ...
    def catch_phrase(self): ...
    def bs(self): ...
