from typing import Any

from .. import Provider as PersonProvider

class Provider(PersonProvider):
    formats_male: Any = ...
    formats_female: Any = ...
    formats: Any = ...
    first_names_male: Any = ...
    first_names_female: Any = ...
    first_names: Any = ...
    last_names: Any = ...
    prefixes_male: Any = ...
    prefixes_female: Any = ...
    prefixes: Any = ...
