from typing import Any, Optional

from .. import BaseProvider as BaseProvider

localized: bool

class Provider(BaseProvider):
    currencies: Any = ...
    cryptocurrencies: Any = ...
    currency_symbols: Any = ...
    def currency(self): ...
    def currency_code(self): ...
    def currency_name(self): ...
    def currency_symbol(self, code: Optional[Any] = ...): ...
    def cryptocurrency(self): ...
    def cryptocurrency_code(self): ...
    def cryptocurrency_name(self): ...
