from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    city_formats: Any = ...
    street_name_formats: Any = ...
    street_address_formats: Any = ...
    address_formats: Any = ...
    building_number_formats: Any = ...
    street_suffixes: Any = ...
    countries: Any = ...
    street_titles: Any = ...
    city_names: Any = ...
    def street_title(self): ...
    def city_name(self): ...
