import matplotlib
from pandas._config import get_option as get_option
from pandas.core.base import PandasObject as PandasObject
from pandas.core.frame import DataFrame
from pandas.core.dtypes.common import is_integer as is_integer, is_list_like as is_list_like
from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCSeries as ABCSeries
from pandas.util._decorators import Appender as Appender, Substitution as Substitution
from typing import Any, Optional, Sequence, Tuple, Union

def hist_series(self, by: Optional[Any] = ..., ax: Optional[Any] = ..., grid: bool = ..., xlabelsize: Optional[Any] = ..., xrot: Optional[Any] = ..., ylabelsize: Optional[Any] = ..., yrot: Optional[Any] = ..., figsize: Optional[Any] = ..., bins: int = ..., backend: Optional[Any] = ..., **kwargs: Any): ...
def hist_frame(data: Any, column: Optional[Any] = ..., by: Optional[Any] = ..., grid: bool = ..., xlabelsize: Optional[Any] = ..., xrot: Optional[Any] = ..., ylabelsize: Optional[Any] = ..., yrot: Optional[Any] = ..., ax: Optional[Any] = ..., sharex: bool = ..., sharey: bool = ..., figsize: Optional[Any] = ..., layout: Optional[Any] = ..., bins: int = ..., backend: Optional[Any] = ..., **kwargs: Any): ...
def boxplot(
    data: DataFrame,
    column: Optional[Union[str, Sequence[str]]] = ...,
    by: Optional[Union[str, Sequence[str]]] = ...,
    ax: Optional[matplotlib.axes.Axes] = ...,
    fontsize: Optional[Union[float, str]] = ...,
    rot: float = ...,
    grid: bool = ...,
    figsize: Optional[Tuple[float, float]] = ...,
    layout: Optional[Tuple[int, int]] = ...,
    return_type: Optional[str] = ...,
) -> Any: ...
def boxplot_frame(self, column: Optional[Any] = ..., by: Optional[Any] = ..., ax: Optional[Any] = ..., fontsize: Optional[Any] = ..., rot: int = ..., grid: bool = ..., figsize: Optional[Any] = ..., layout: Optional[Any] = ..., return_type: Optional[Any] = ..., backend: Optional[Any] = ..., **kwargs: Any): ...
def boxplot_frame_groupby(grouped: Any, subplots: bool = ..., column: Optional[Any] = ..., fontsize: Optional[Any] = ..., rot: int = ..., grid: bool = ..., ax: Optional[Any] = ..., figsize: Optional[Any] = ..., layout: Optional[Any] = ..., sharex: bool = ..., sharey: bool = ..., backend: Optional[Any] = ..., **kwargs: Any): ...

class PlotAccessor(PandasObject):
    def __init__(self, data: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any): ...
    def line(self, x: Optional[Any] = ..., y: Optional[Any] = ..., **kwargs: Any): ...
    def bar(self, x: Optional[Any] = ..., y: Optional[Any] = ..., **kwargs: Any): ...
    def barh(self, x: Optional[Any] = ..., y: Optional[Any] = ..., **kwargs: Any): ...
    def box(self, by: Optional[Any] = ..., **kwargs: Any): ...
    def hist(self, by: Optional[Any] = ..., bins: int = ..., **kwargs: Any): ...
    def kde(self, bw_method: Optional[Any] = ..., ind: Optional[Any] = ..., **kwargs: Any): ...
    density: Any = ...
    def area(self, x: Optional[Any] = ..., y: Optional[Any] = ..., **kwargs: Any): ...
    def pie(self, **kwargs: Any): ...
    def scatter(self, x: Any, y: Any, s: Optional[Any] = ..., c: Optional[Any] = ..., **kwargs: Any): ...
    def hexbin(self, x: Any, y: Any, C: Optional[Any] = ..., reduce_C_function: Optional[Any] = ..., gridsize: Optional[Any] = ..., **kwargs: Any): ...
