"""
This type stub file was generated by pyright.
"""

import os
from .utils.objects import cached_property

"""Logging Utilities."""
DISABLE_TRACEBACKS = os.environ.get('DISABLE_TRACEBACKS')
def get_logger(logger):
    """Get logger by name."""
    ...

def get_loglevel(level):
    """Get loglevel by name."""
    ...

def naive_format_parts(fmt):
    ...

def safeify_format(fmt, args, filters=...):
    ...

class LogMixin:
    """Mixin that adds severity methods to any class."""
    def debug(self, *args, **kwargs):
        ...
    
    def info(self, *args, **kwargs):
        ...
    
    def warn(self, *args, **kwargs):
        ...
    
    def error(self, *args, **kwargs):
        ...
    
    def critical(self, *args, **kwargs):
        ...
    
    def annotate(self, text):
        ...
    
    def log(self, severity, *args, **kwargs):
        ...
    
    def get_logger(self):
        ...
    
    def is_enabled_for(self, level):
        ...
    
    def get_loglevel(self, level):
        ...
    
    @cached_property
    def logger(self):
        ...
    
    @property
    def logger_name(self):
        ...
    


class Log(LogMixin):
    def __init__(self, name, logger=...) -> None:
        ...
    
    def get_logger(self):
        ...
    
    @property
    def logger_name(self):
        ...
    


def setup_logging(loglevel=..., logfile=...):
    """Setup logging."""
    ...

