from sympy.assumptions import Predicate

class FinitePredicate(Predicate):
    name = ...
    handler = ...

class InfinitePredicate(Predicate):
    name = ...
    handler = ...

class PositiveInfinitePredicate(Predicate):
    name = ...
    handler = ...

class NegativeInfinitePredicate(Predicate):
    name = ...
    handler = ...
