from sympy.assumptions import Predicate

class IntegerPredicate(Predicate):
    name = ...
    handler = ...

class NonIntegerPredicate(Predicate):
    name = ...
    handler = ...

class RationalPredicate(Predicate):
    name = ...
    handler = ...

class IrrationalPredicate(Predicate):
    name = ...
    handler = ...

class RealPredicate(Predicate):
    name = ...
    handler = ...

class ExtendedRealPredicate(Predicate):
    name = ...
    handler = ...

class HermitianPredicate(Predicate):
    name = ...
    handler = ...

class ComplexPredicate(Predicate):
    name = ...
    handler = ...

class ImaginaryPredicate(Predicate):
    name = ...
    handler = ...

class AntihermitianPredicate(Predicate):
    name = ...
    handler = ...

class AlgebraicPredicate(Predicate):
    name = ...
    AlgebraicHandler = ...

class TranscendentalPredicate(Predicate):
    name = ...
    handler = ...
