from typing import Any

def days_in_year(*args, **kwargs) -> Any: ...
def is_leap(*args, **kwargs) -> Any: ...
def is_long_year(*args, **kwargs) -> Any: ...
def local_time(*args, **kwargs) -> Any: ...
def precise_diff(*args, **kwargs) -> Any: ...
def timestamp(*args, **kwargs) -> Any: ...
def week_day(*args, **kwargs) -> Any: ...

class PreciseDiff:
    days: Any = ...
    hours: Any = ...
    microseconds: Any = ...
    minutes: Any = ...
    months: Any = ...
    seconds: Any = ...
    total_days: Any = ...
    years: Any = ...
    def __init__(self, *args, **kwargs) -> None: ...
