from . import dml as dml, elements as elements
from .. import exc as exc, util as util
from typing import Any

REQUIRED: Any
ISINSERT: Any
ISUPDATE: Any
ISDELETE: Any

class _multiparam_column(elements.ColumnElement):
    index: Any = ...
    key: Any = ...
    original: Any = ...
    default: Any = ...
    type: Any = ...
    def __init__(self, original: Any, index: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
