import os
import sys
import warnings
from copy import deepcopy
from functools import partial
from os import path as op

from numpy.typing import ArrayLike

from ..util import run_subprocess, use_log_level
from ..util.ptime import time
from ._testing import IS_CI, IS_TRAVIS_CI, has_application, nottest

# -*- coding: utf-8 -*-
# vispy: testskip
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.

_line_sep = ...

class VispySkipSuite(Exception):
    def __init__(self, msg=""): ...

def _get_import_dir(): ...
def _unit(mode, extra_arg_string="", coverage=False): ...
def _docs(): ...
def _flake(): ...
def _check_line_endings(): ...

_script: str = ...

bad_examples: list = ...

def _skip_example(fname): ...
def _examples(fnames_str): ...
@nottest
def test(label: str = "full", extra_arg_string: str | ArrayLike = "", coverage: bool = False): ...
