from .. import Provider as PhoneNumberProvider
from typing import Any

class Provider(PhoneNumberProvider):
    phonenumber_prefixes: Any = ...
    formats: Any = ...
    def phonenumber_prefix(self): ...
