from typing import Any

from .. import Provider as PhoneNumberProvider

class Provider(PhoneNumberProvider):
    phonenumber_prefixes: Any = ...
    formats: Any = ...
    def phonenumber_prefix(self): ...
