from typing import Any

from .. import Provider as AddressProvider

class Provider(AddressProvider):
    city_suffixes: Any = ...
    city_prefixes: Any = ...
    street_prefixes: Any = ...
    address_formats: Any = ...
    building_number_formats: Any = ...
    city_formats: Any = ...
    street_address_formats: Any = ...
    street_name_formats: Any = ...
    postcode_formats: Any = ...
    cantons: Any = ...
    countries: Any = ...
    def street_prefix(self): ...
    def city_prefix(self): ...
    def canton(self): ...
    def canton_name(self): ...
    def canton_code(self): ...
