from .. import Provider as DateTimeProvider
from typing import Any

class Provider(DateTimeProvider):
    DAY_NAMES: Any = ...
    MONTH_NAMES: Any = ...
    countries: Any = ...
    def day_of_week(self): ...
    def month_name(self): ...
