from collections import abc
#from pandas.io.common import get_filepath_or_buffer as get_filepath_or_buffer
#from pandas.util._decorators import Appender as Appender
from typing import Any, Optional

class XportReader(abc.Iterator):
    __doc__: Any = ...
    filepath_or_buffer: Any = ...
    def __init__(self, filepath_or_buffer: Any, index: Optional[Any] = ..., encoding: str = ..., chunksize: Optional[Any] = ...) -> None: ...
    def close(self) -> None: ...
    def __next__(self): ...
    def get_chunk(self, size: Optional[Any] = ...): ...
    def read(self, nrows: Optional[Any] = ...): ...
