from collections.abc import Generator
from typing import Any, Callable

def identity(x) -> Generator[Any]: ...
def exhaust(brule) -> Callable[..., Generator[Any]]: ...
def onaction(brule, fn) -> Callable[..., Generator[Any]]: ...
def debug(brule, file=...) -> Callable[..., Generator[Any]]: ...
def multiplex(*brules) -> Callable[..., Generator[Any]]: ...
def condition(cond, brule) -> Callable[..., Generator[Any]]: ...
def sfilter(pred, brule) -> Callable[..., Generator[Any]]: ...
def notempty(brule) -> Callable[..., Generator[Any]]: ...
def do_one(*brules) -> Callable[..., Generator[Any]]: ...
def chain(*brules) -> Callable[..., Generator[Any]]: ...
def yieldify(rl) -> Callable[..., Generator[Any]]: ...
