from collections.abc import Generator
from typing import Any, Callable

def top_down(brule, fns=...) -> Callable[..., Generator[Any]]: ...
def sall(brule, fns=...) -> Callable[..., Generator[Any]]: ...
