name: 'Docify'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run:
          python -m pip install -r utils/requirements.txt

      - name: Install partial pandas stubs
        run:
          cp -R partial/ typings

      - name: Install docify
        run:
          PBR_VERSION=1.0.0 pip install utils/docify

      - name: Run docify
        run:
          docify utils/build_bundle/docify-pandas.cfg typings/pandas

